var builder = WebApplication.CreateBuilder(args);

// Generated by GitHub Copilot
builder.Services.AddCors(options =>
{
    options.AddPolicy("LocalClientApps", policy =>
    {
        policy
            .SetIsOriginAllowed(static origin =>
                Uri.TryCreate(origin, UriKind.Absolute, out var uri)
                && (uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase)
                    || uri.Host.Equals("127.0.0.1", StringComparison.OrdinalIgnoreCase)))
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});
builder.Services.AddOpenApi();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();
app.UseCors("LocalClientApps");

var people = new[]
{
    new Person(1, "Mina Patel", "Product Strategy Lead", "Toronto", "mina.patel@example.com"),
    new Person(2, "Jonah Reed", "Platform Engineer", "Montreal", "jonah.reed@example.com"),
    new Person(3, "Alina Cho", "Delivery Manager", "Vancouver", "alina.cho@example.com"),
    new Person(4, "Noah Bennett", "Business Analyst", "Calgary", "noah.bennett@example.com"),
    new Person(5, "Sofia Nguyen", "UX Researcher", "Ottawa", "sofia.nguyen@example.com")
};

app.MapGet("/api/people", () => TypedResults.Ok(people))
    .WithName("GetPeople");

app.Run();

internal sealed record Person(int Id, string Name, string Role, string Location, string Email);
