<%-- Generated by GitHub Copilot --%>
<%@ Page Title="Legacy Host" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="LegacyHost.WebForms._Default" %>

<asp:Content ID="TitleContent" ContentPlaceHolderID="HeadContent" runat="server">
    <link rel="stylesheet" href="/ClientApp/people-app.css" />
    <style>
        .legacy-shell {
            margin-bottom: 24px;
        }

        .legacy-shell h2 {
            margin: 0 0 8px;
        }
    </style>
</asp:Content>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <section class="legacy-shell">
        <h2>Legacy host with injected React people component</h2>
        <p>The component below is rendered by the shared React app and populated from ModernApi.</p>
    </section>
    <div data-people-app="true" data-api-base-url="<%= PeopleApiBaseUrl %>" data-host-display-name="LegacyHost.WebForms"></div>
    <script type="module" src="/ClientApp/people-app.js"></script>
</asp:Content>