// Generated by GitHub Copilot

namespace LegacyHost.WebForms
{
    /// <summary>
    /// Defines the server-side controls declared in the default content page.
    /// </summary>
    public partial class _Default
    {
        /// <summary>
        /// Provides content for the head placeholder in the site master page.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content TitleContent;

        /// <summary>
        /// Provides content for the main placeholder in the site master page.
        /// </summary>
        protected global::System.Web.UI.WebControls.Content BodyContent;
    }
}