// Generated by GitHub Copilot

namespace LegacyHost.WebForms
{
    /// <summary>
    /// Defines the server-side controls declared in the site master page.
    /// </summary>
    public partial class SiteMaster
    {
        /// <summary>
        /// Gets the HTML head element for the master page.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlHead HeadElement;

        /// <summary>
        /// Provides a content placeholder for page-specific head content.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// Gets the root HTML form for the page.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm MainForm;

        /// <summary>
        /// Provides a content placeholder for page body content.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}