// Generated by GitHub Copilot
using System.Web.UI;

namespace LegacyHost.WebForms
{
    /// <summary>
    /// Represents the shared site master used by the legacy Web Forms host.
    /// </summary>
    public partial class SiteMaster : MasterPage
    {
    }
}