@echo off
REM Generated by GitHub Copilot
where pwsh >nul 2>nul
if %ERRORLEVEL%==0 (
    pwsh -ExecutionPolicy Bypass -File "%~dp0run-all.ps1" %*
    exit /b %ERRORLEVEL%
)

powershell -ExecutionPolicy Bypass -File "%~dp0run-all.ps1" %*