# Generated by GitHub Copilot
[CmdletBinding()]
param(
    [switch]$SkipBuild,
    [switch]$SkipLegacyHost,
    [switch]$NoBrowser
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-ShellPath {
    $pwshCommand = Get-Command pwsh.exe -ErrorAction SilentlyContinue

    if ($pwshCommand) {
        return $pwshCommand.Source
    }

    $powershellCommand = Get-Command powershell.exe -ErrorAction SilentlyContinue

    if ($powershellCommand) {
        return $powershellCommand.Source
    }

    throw 'Neither pwsh.exe nor powershell.exe was found on PATH.'
}

function Resolve-ApplicationHostPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepositoryRoot
    )

    $legacyProjectPath = Join-Path $RepositoryRoot 'src\LegacyHost.WebForms'

    if (-not [string]::IsNullOrWhiteSpace($env:PLAYWRIGHT_APPLICATIONHOST_PATH) -and (Test-Path $env:PLAYWRIGHT_APPLICATIONHOST_PATH)) {
        return $env:PLAYWRIGHT_APPLICATIONHOST_PATH
    }

    $preferredPath = Join-Path $RepositoryRoot '.vs\WebFormReactMVC.slnx\config\applicationhost.config'

    if ((Test-Path $preferredPath) -and ((Get-Content -Path $preferredPath -Raw) -like "*$legacyProjectPath*")) {
        return $preferredPath
    }

    $visualStudioDirectory = Join-Path $RepositoryRoot '.vs'

    if (-not (Test-Path $visualStudioDirectory)) {
        return $null
    }

    $applicationHostFile = Get-ChildItem -Path $visualStudioDirectory -Directory |
        ForEach-Object {
            Join-Path $_.FullName 'config\applicationhost.config'
        } |
        Where-Object {
            (Test-Path $_) -and ((Get-Content -Path $_ -Raw) -like "*$legacyProjectPath*")
        } |
        Select-Object -First 1

    return $applicationHostFile
}

function Start-RepoProcess {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory = $true)]
        [string]$Title,

        [Parameter(Mandatory = $true)]
        [string]$Command
    )

    $shellPath = Resolve-ShellPath
    $bootstrapCommand = "Set-Location '$RepositoryRoot'; `$Host.UI.RawUI.WindowTitle = '$Title'; $Command"

    Start-Process -FilePath $shellPath -ArgumentList '-NoExit', '-Command', $bootstrapCommand | Out-Null
    Write-Host "Started $Title" -ForegroundColor Green
}

function Start-LegacyHost {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepositoryRoot
    )

    $iisExpressPath = if (-not [string]::IsNullOrWhiteSpace($env:PLAYWRIGHT_IIS_EXPRESS_PATH)) {
        $env:PLAYWRIGHT_IIS_EXPRESS_PATH
    }
    else {
        'C:\Program Files\IIS Express\iisexpress.exe'
    }

    if (-not (Test-Path $iisExpressPath)) {
        Write-Warning "LegacyHost.WebForms was not started because IIS Express was not found at '$iisExpressPath'."
        return $false
    }

    $applicationHostPath = Resolve-ApplicationHostPath -RepositoryRoot $RepositoryRoot

    if ($applicationHostPath) {
        Start-Process -FilePath $iisExpressPath -ArgumentList @(
            '/site:LegacyHost.WebForms',
            "/config:$applicationHostPath"
        ) | Out-Null

        Write-Host 'Started LegacyHost.WebForms with IIS Express site configuration' -ForegroundColor Green
        return $true
    }

    $legacyProjectPath = Join-Path $RepositoryRoot 'src\LegacyHost.WebForms'

    Start-Process -FilePath $iisExpressPath -ArgumentList @(
        "/path:$legacyProjectPath",
        '/port:63755'
    ) | Out-Null

    Write-Host 'Started LegacyHost.WebForms with IIS Express path mode on http://localhost:63755' -ForegroundColor Yellow
    return $true
}

$repositoryRoot = Split-Path -Parent $PSCommandPath
Set-Location $repositoryRoot

Write-Host 'Repository root:' $repositoryRoot -ForegroundColor Cyan

if (-not $SkipBuild) {
    Write-Host 'Building solution...' -ForegroundColor Cyan
    dotnet build .\WebFormReactMVC.slnx

    if ($LASTEXITCODE -ne 0) {
        throw 'dotnet build failed. Fix the build errors and run the script again.'
    }
}

Start-RepoProcess -RepositoryRoot $repositoryRoot -Title 'ModernApi' -Command 'dotnet run --project ".\src\ModernApi\ModernApi.csproj" --launch-profile https'
Start-RepoProcess -RepositoryRoot $repositoryRoot -Title 'ModernHost.Mvc' -Command 'dotnet run --project ".\src\ModernHost.Mvc\ModernHost.Mvc.csproj" --launch-profile https'

$legacyHostStarted = $false

if (-not $SkipLegacyHost) {
    $legacyHostStarted = Start-LegacyHost -RepositoryRoot $repositoryRoot
}

if (-not $NoBrowser) {
    Start-Process 'https://localhost:7184/' | Out-Null

    if ($legacyHostStarted) {
        Start-Process 'http://localhost:63755/Default.aspx' | Out-Null
    }
}

Write-Host ''
Write-Host 'Application URLs:' -ForegroundColor Cyan
Write-Host '  Modern API:      https://localhost:7114/api/people?page=1&pageSize=25'
Write-Host '  Modern MVC host: https://localhost:7184/'

if ($legacyHostStarted) {
    Write-Host '  Legacy host:     http://localhost:63755/Default.aspx'
}
elseif (-not $SkipLegacyHost) {
    Write-Host '  Legacy host:     Not started automatically. Start it from Visual Studio or install IIS Express.' -ForegroundColor Yellow
}

Write-Host ''
Write-Host 'Use -SkipBuild to reuse the current build, -SkipLegacyHost to start only the API and MVC host, or -NoBrowser to skip opening pages.' -ForegroundColor DarkGray