// Generated by GitHub Copilot
using System.Configuration;
using System.Web.UI;

namespace LegacyHost.WebForms
{
    /// <summary>
    /// Represents the default landing page for the legacy Web Forms host.
    /// </summary>
    public partial class _Default : Page
    {
        /// <summary>
        /// Gets the ModernApi base URL used by the injected React people component.
        /// </summary>
        protected string PeopleApiBaseUrl =>
            ConfigurationManager.AppSettings["ModernApiBaseUrl"] ?? "https://localhost:7114";
    }
}