// Generated by GitHub Copilot
using System.Web;

namespace LegacyHost.WebForms
{
    /// <summary>
    /// Represents the ASP.NET application entry point for the legacy Web Forms host.
    /// </summary>
    public class Global : HttpApplication
    {
    }
}