// Generated by GitHub Copilot
import { defineConfig, devices } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const currentDirectory = path.dirname(fileURLToPath(import.meta.url))
const repositoryRoot = path.resolve(currentDirectory, '..')
const legacyProjectPath = path.resolve(repositoryRoot, 'src', 'LegacyHost.WebForms')
const iisExpressPath =
  process.env.PLAYWRIGHT_IIS_EXPRESS_PATH ??
  'C:\\Program Files\\IIS Express\\iisexpress.exe'

/**
 * Resolves the IIS Express applicationHost.config path without depending on a single .vs solution folder name.
 */
function resolveApplicationHostPath() {
  const configuredPath = process.env.PLAYWRIGHT_APPLICATIONHOST_PATH

  if (configuredPath) {
    return configuredPath
  }

  const preferredPath = path.resolve(
    repositoryRoot,
    '.vs',
    'WebFormReactMVC.slnx',
    'config',
    'applicationhost.config',
  )

  if (fs.existsSync(preferredPath)) {
    return preferredPath
  }

  const visualStudioDirectory = path.resolve(repositoryRoot, '.vs')

  if (!fs.existsSync(visualStudioDirectory)) {
    return null
  }

  for (const entry of fs.readdirSync(visualStudioDirectory, { withFileTypes: true })) {
    if (!entry.isDirectory()) {
      continue
    }

    const candidatePath = path.resolve(
      visualStudioDirectory,
      entry.name,
      'config',
      'applicationhost.config',
    )

    if (!fs.existsSync(candidatePath)) {
      continue
    }

    const applicationHostContent = fs.readFileSync(candidatePath, 'utf8')

    if (applicationHostContent.includes(legacyProjectPath)) {
      return candidatePath
    }
  }

  return null
}

const applicationHostPath = resolveApplicationHostPath()
const legacyHostBaseUrl = process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:63755'
const modernHostBaseUrl = process.env.PLAYWRIGHT_MVC_BASE_URL ?? 'https://localhost:7184'
const modernApiBaseUrl = process.env.PLAYWRIGHT_API_URL ?? 'https://localhost:7114'
const modernApiReadyUrl =
  process.env.PLAYWRIGHT_API_READY_URL ?? 'https://localhost:7114/api/people'
const legacyHostCommand =
  process.env.PLAYWRIGHT_LEGACY_HOST_COMMAND ??
  (applicationHostPath
    ? `"${iisExpressPath}" /site:LegacyHost.WebForms /config:"${applicationHostPath}"`
    : `"${iisExpressPath}" /path:"${legacyProjectPath}" /port:63755`)
const modernHostCommand = `dotnet run --project "${path.resolve(
  repositoryRoot,
  'src',
  'ModernHost.Mvc',
  'ModernHost.Mvc.csproj',
)}" --launch-profile https`
const modernApiCommand =
  process.env.PLAYWRIGHT_API_COMMAND ??
  `dotnet run --project "${path.resolve(repositoryRoot, 'src', 'ModernApi', 'ModernApi.csproj')}" --launch-profile https`

export default defineConfig({
  testDir: './specs',
  fullyParallel: false,
  timeout: 30_000,
  expect: {
    timeout: 10_000,
  },
  reporter: [['list'], ['html', { open: 'never' }]],
  outputDir: 'test-results',
  use: {
    ignoreHTTPSErrors: true,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  webServer: [
    {
      command: modernApiCommand,
      url: modernApiReadyUrl,
      ignoreHTTPSErrors: true,
      name: 'ModernApi',
      timeout: 120_000,
      reuseExistingServer: !process.env.CI,
    },
    {
      command: legacyHostCommand,
      url: `${legacyHostBaseUrl}/Default.aspx`,
      name: 'LegacyHost.WebForms',
      timeout: 120_000,
      reuseExistingServer: !process.env.CI,
    },
    {
      command: modernHostCommand,
      url: modernHostBaseUrl,
      ignoreHTTPSErrors: true,
      name: 'ModernHost.Mvc',
      timeout: 120_000,
      reuseExistingServer: !process.env.CI,
    },
  ],
  projects: [
    {
      name: 'legacy-host-chromium',
      testMatch: /.*\.page\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        baseURL: legacyHostBaseUrl,
      },
    },
    {
      name: 'modern-api',
      testMatch: /.*\.api\.spec\.ts/,
      use: {
        baseURL: modernApiBaseUrl,
        extraHTTPHeaders: {
          Accept: 'application/json',
        },
      },
    },
  ],
})