// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'

const expectedPeopleEndpoint = `${
  (process.env.PLAYWRIGHT_API_URL ?? 'https://localhost:7114').replace(/\/$/, '')
}/api/people`

test.describe('LegacyHost.WebForms Default.aspx', () => {
  test('renders the React people directory inside the Web Forms page with the legacy host label', async ({
    page,
  }) => {
    await page.goto('/Default.aspx')

    await expect(page).toHaveTitle(/Legacy Host - LegacyHost\.WebForms/)
    await expect(
      page.getByRole('heading', {
        name: 'Legacy host with injected React people component',
      }),
    ).toBeVisible()
    await expect(page.getByRole('heading', { name: 'People directory' })).toBeVisible()
    await expect(page.getByRole('region', { name: 'Who is editing right now' })).toBeVisible()
    await expect(page.locator('.people-hero__summary')).toContainText(
      'This instance is currently hosted by LegacyHost.WebForms.',
    )
    await expect(page.getByRole('region', { name: 'Directory results' })).toContainText(
      expectedPeopleEndpoint,
    )

    const peopleList = page.getByRole('list', {
      name: 'People returned from ModernApi',
    })

    await expect(peopleList).toBeVisible()
    await expect(peopleList.getByRole('listitem')).toHaveCount(5)
    await expect(page.getByRole('heading', { name: 'Mina Patel' })).toBeVisible()
    await expect(
      page.getByRole('link', { name: 'mina.patel@example.com' }),
    ).toHaveAttribute('href', 'mailto:mina.patel@example.com')
  })

  test('opens the in-page edit dialog for a person and exposes accessible form fields', async ({
    page,
  }) => {
    await page.goto('/Default.aspx')

    const minaCard = page.getByRole('listitem').filter({
      has: page.getByRole('heading', { name: 'Mina Patel' }),
    })

    await minaCard.getByRole('button', { name: 'Edit' }).click()

    const dialog = page.getByRole('dialog', { name: 'Mina Patel' })

    await expect(dialog).toBeVisible()
    await expect(dialog.getByLabel('Name')).toHaveValue('Mina Patel')
    await expect(dialog.getByLabel('Role')).toHaveValue('Product Strategy Lead')
    await expect(dialog.getByLabel('Location')).toHaveValue('Toronto')
    await expect(dialog.getByLabel('Email')).toHaveValue('mina.patel@example.com')

    await dialog.getByRole('button', { name: 'Cancel' }).click()
    await expect(dialog).toBeHidden()
  })
})