// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'
import {
  defaultDirectorySummary,
  defaultPagerSummary,
  directorySummary,
  expectSharedDirectoryChrome,
  getVisiblePeopleNames,
  pagerStatus,
  peopleList,
  readPeoplePayload,
  restorablePerson2500,
  waitForPeopleResponse,
  expectedPeopleEndpoint,
} from './people-directory-test-helpers'

const torontoDirectorySummary = 'Showing 1-25 of 211 people'
const torontoPagerSummary = 'Page 1 of 9'

test.describe('LegacyHost.WebForms Default.aspx', () => {
  test('renders the paged people directory inside the Web Forms page with the legacy host label', async ({
    page,
  }) => {
    const defaultResponsePromise = waitForPeopleResponse(page, (requestUrl) => requestUrl.search === '')

    await page.goto('/Default.aspx')

    const payload = await readPeoplePayload(await defaultResponsePromise)

    expect(payload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 2500,
      totalPages: 100,
      hasPreviousPage: false,
      hasNextPage: true,
    })
    expect(payload.items).toHaveLength(25)

    await expect(page).toHaveTitle(/Legacy Host - LegacyHost\.WebForms/)
    await expect(
      page.getByRole('heading', {
        name: 'Legacy host with injected React people component',
      }),
    ).toBeVisible()
    await expectSharedDirectoryChrome(page, 'LegacyHost.WebForms')
    await expect(page.getByRole('button', { name: 'Reset view' })).toBeDisabled()
    await expect(page.getByLabel('Page size')).toHaveValue('25')
    await expect(directorySummary(page)).toHaveText(defaultDirectorySummary)
    await expect(pagerStatus(page)).toHaveText(defaultPagerSummary)
    await expect(peopleList(page)).toBeVisible()
    await expect(peopleList(page).getByRole('listitem')).toHaveCount(25)
  })

  test('updates paging, resets filters back to page 1, and restores the default view', async ({
    page,
  }) => {
    const defaultResponsePromise = waitForPeopleResponse(page, (requestUrl) => requestUrl.search === '')

    await page.goto('/Default.aspx')
    await readPeoplePayload(await defaultResponsePromise)

    const firstPageNames = await getVisiblePeopleNames(page)

    expect(firstPageNames).toHaveLength(25)

    const secondPageResponsePromise = waitForPeopleResponse(
      page,
      (requestUrl) => requestUrl.searchParams.get('page') === '2',
    )
    await page.getByRole('button', { name: 'Next' }).click()

    const secondPagePayload = await readPeoplePayload(await secondPageResponsePromise)

    expect(secondPagePayload).toMatchObject({
      page: 2,
      pageSize: 25,
      totalCount: 2500,
      totalPages: 100,
      hasPreviousPage: true,
      hasNextPage: true,
    })

    await expect(page).toHaveURL(/page=2/)
    await expect(directorySummary(page)).toHaveText('Showing 26-50 of 2500 people')
    await expect(pagerStatus(page)).toHaveText('Page 2 of 100')

    const secondPageNames = await getVisiblePeopleNames(page)

    expect(secondPageNames).toHaveLength(25)
    expect(secondPageNames[0]).not.toBe(firstPageNames[0])
    await expect(page.getByRole('heading', { name: firstPageNames[0] })).toBeHidden()

    const filteredResponsePromise = waitForPeopleResponse(
      page,
      (requestUrl) =>
        requestUrl.searchParams.get('location') === 'Toronto'
        && !requestUrl.searchParams.has('page'),
    )
    await page.getByRole('textbox', { name: 'Location' }).fill('Toronto')

    const filteredPayload = await readPeoplePayload(await filteredResponsePromise)

    expect(filteredPayload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 211,
      totalPages: 9,
      hasPreviousPage: false,
      hasNextPage: true,
      appliedFilters: {
        search: null,
        location: 'Toronto',
        role: null,
        sortBy: 'name',
        sortDirection: 'asc',
      },
    })

    await expect(page).toHaveURL(/location=Toronto/)
    expect(new URL(page.url()).searchParams.has('page')).toBe(false)
    await expect(directorySummary(page)).toHaveText(torontoDirectorySummary)
    await expect(pagerStatus(page)).toHaveText(torontoPagerSummary)
    await expect(page.getByRole('button', { name: 'Reset view' })).toBeEnabled()

    const resetResponsePromise = waitForPeopleResponse(page, (requestUrl) => requestUrl.search === '')
    await page.getByRole('button', { name: 'Reset view' }).click()

    const resetPayload = await readPeoplePayload(await resetResponsePromise)

    expect(resetPayload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 2500,
      totalPages: 100,
      hasPreviousPage: false,
      hasNextPage: true,
      appliedFilters: {
        search: null,
        location: null,
        role: null,
        sortBy: 'name',
        sortDirection: 'asc',
      },
    })

    await expect(directorySummary(page)).toHaveText(defaultDirectorySummary)
    await expect(pagerStatus(page)).toHaveText(defaultPagerSummary)
    await expect(page.getByRole('textbox', { name: 'Location' })).toHaveValue('')
    await expect(page.getByRole('button', { name: 'Reset view' })).toBeDisabled()
    expect(new URL(page.url()).search).toBe('')
  })

  test('opens the in-page edit dialog after locating a person through filters', async ({
    page,
    request,
  }) => {
    const defaultResponsePromise = waitForPeopleResponse(page, (requestUrl) => requestUrl.search === '')

    await page.goto('/Default.aspx')
    await readPeoplePayload(await defaultResponsePromise)

    const filteredResponsePromise = waitForPeopleResponse(
      page,
      (requestUrl) => requestUrl.searchParams.get('search') === restorablePerson2500.email,
    )
    await page.getByLabel('Search').fill(restorablePerson2500.email)

    const filteredPayload = await readPeoplePayload(await filteredResponsePromise)

    expect(filteredPayload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 1,
      totalPages: 1,
      hasPreviousPage: false,
      hasNextPage: false,
      appliedFilters: {
        search: restorablePerson2500.email,
        location: null,
        role: null,
        sortBy: 'name',
        sortDirection: 'asc',
      },
    })

    await expect(directorySummary(page)).toHaveText('Showing 1-1 of 1 people')

    const personCard = peopleList(page).getByRole('listitem').first()
    const updatedRole = `${restorablePerson2500.role} Coverage`

    try {
      await personCard.getByRole('button', { name: 'Edit' }).click()

      const dialog = page.getByRole('dialog', { name: restorablePerson2500.name })

      await expect(dialog).toBeVisible()
      await expect(dialog.getByLabel('Name')).toHaveValue(restorablePerson2500.name)
      await expect(dialog.getByLabel('Role')).toHaveValue(restorablePerson2500.role)
      await expect(dialog.getByLabel('Location')).toHaveValue(restorablePerson2500.location)
      await expect(dialog.getByLabel('Email')).toHaveValue(restorablePerson2500.email)

      const saveResponsePromise = page.waitForResponse(
        (response) =>
          response.request().method() === 'PUT'
          && response.url() === `${expectedPeopleEndpoint}/${restorablePerson2500.id}`,
      )
      await dialog.getByLabel('Role').fill(updatedRole)
      await dialog.getByRole('button', { name: 'Save' }).click()

      const saveResponse = await saveResponsePromise

      expect(saveResponse.ok()).toBeTruthy()

      await expect(dialog).toBeHidden()
      await expect(personCard).toContainText(updatedRole)
    } finally {
      const restoreResponse = await request.put(
        `${expectedPeopleEndpoint}/${restorablePerson2500.id}`,
        {
          data: restorablePerson2500,
        },
      )

      expect(restoreResponse.ok()).toBeTruthy()
    }
  })
})