// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'

const legacyHostPageUrl = `${(process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:63755').replace(
  /\/$/,
  '',
)}/Default.aspx`
const modernHostBaseUrl = (process.env.PLAYWRIGHT_MVC_BASE_URL ?? 'https://localhost:7184').replace(
  /\/$/,
  '',
)

test.describe('Shared people app across hosts', () => {
  test('shows distinct host labels and shares live editing presence between legacy and MVC hosts', async ({
    context,
    page,
  }) => {
    const modernHostPage = await context.newPage()

    await page.goto(legacyHostPageUrl)
    await modernHostPage.goto(modernHostBaseUrl)

    await expect(page.locator('.people-hero__summary')).toContainText(
      'This instance is currently hosted by LegacyHost.WebForms.',
    )
    await expect(modernHostPage.locator('.people-hero__summary')).toContainText(
      'This instance is currently hosted by ModernHost.Mvc.',
    )

    await expect(page.getByText('Live presence connected')).toBeVisible()
    await expect(modernHostPage.getByText('Live presence connected')).toBeVisible()

    await page.getByLabel('Your display name').fill('Legacy Host Editor')
    await modernHostPage.getByLabel('Your display name').fill('Modern Host Observer')

    const legacyMinaCard = page.getByRole('listitem').filter({
      has: page.getByRole('heading', { name: 'Mina Patel' }),
    })

    await legacyMinaCard.getByRole('button', { name: 'Edit' }).click()
    await expect(page.getByRole('dialog', { name: 'Mina Patel' })).toBeVisible()
    await expect(
      modernHostPage.getByRole('list', {
        name: 'Active editing presence',
      }),
    ).toContainText('Legacy Host Editor editing Mina Patel')

    await page.getByRole('button', { name: 'Cancel' }).click()
    await expect(page.getByRole('dialog', { name: 'Mina Patel' })).toBeHidden()

    await modernHostPage.close()
  })
})