// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'

const modernHostBaseUrl = (process.env.PLAYWRIGHT_MVC_BASE_URL ?? 'https://localhost:7184').replace(
  /\/$/,
  '',
)
const expectedPeopleEndpoint = `${
  (process.env.PLAYWRIGHT_API_URL ?? 'https://localhost:7114').replace(/\/$/, '')
}/api/people`

test.describe('ModernHost.Mvc', () => {
  test('renders the shared React people directory with the MVC host label', async ({ page }) => {
    await page.goto(modernHostBaseUrl)

    await expect(page).toHaveTitle(/People Directory - ModernHost\.Mvc/)
    await expect(page.getByRole('link', { name: 'ModernHost.Mvc' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'People directory' })).toBeVisible()
    await expect(page.getByRole('region', { name: 'Who is editing right now' })).toBeVisible()
    await expect(page.locator('.people-hero__summary')).toContainText(
      'This instance is currently hosted by ModernHost.Mvc.',
    )
    await expect(page.getByRole('region', { name: 'Directory results' })).toContainText(
      expectedPeopleEndpoint,
    )

    const peopleList = page.getByRole('list', {
      name: 'People returned from ModernApi',
    })

    await expect(peopleList).toBeVisible()
    await expect(peopleList.getByRole('listitem')).toHaveCount(5)
    await expect(page.getByRole('heading', { name: 'Mina Patel' })).toBeVisible()
  })
})