// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'
import {
  defaultDirectorySummary,
  defaultPagerSummary,
  directorySummary,
  expectSharedDirectoryChrome,
  modernHostBaseUrl,
  pagerStatus,
  peopleList,
  readPeoplePayload,
  waitForPeopleResponse,
} from './people-directory-test-helpers'

test.describe('ModernHost.Mvc', () => {
  test('renders the shared React people directory with paged results on the MVC host', async ({
    page,
  }) => {
    const defaultResponsePromise = waitForPeopleResponse(page, (requestUrl) => requestUrl.search === '')

    await page.goto(modernHostBaseUrl)

    const payload = await readPeoplePayload(await defaultResponsePromise)

    expect(payload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 2500,
      totalPages: 100,
      hasPreviousPage: false,
      hasNextPage: true,
    })
    expect(payload.items).toHaveLength(25)

    await expect(page).toHaveTitle(/People Directory - ModernHost\.Mvc/)
    await expect(page.getByRole('link', { name: 'ModernHost.Mvc' })).toBeVisible()
    await expectSharedDirectoryChrome(page, 'ModernHost.Mvc')
    await expect(page.getByRole('button', { name: 'Reset view' })).toBeDisabled()
    await expect(page.getByLabel('Page size')).toHaveValue('25')
    await expect(directorySummary(page)).toHaveText(defaultDirectorySummary)
    await expect(pagerStatus(page)).toHaveText(defaultPagerSummary)
    await expect(peopleList(page).getByRole('listitem')).toHaveCount(25)
  })

  test('honors URL query state, resets filtered views to page 1, and clears back to default', async ({
    page,
  }) => {
    const initialUrl = `${modernHostBaseUrl}?page=3&pageSize=10&sortBy=id&sortDirection=desc`
    const initialResponsePromise = waitForPeopleResponse(
      page,
      (requestUrl) =>
        requestUrl.searchParams.get('page') === '3'
        && requestUrl.searchParams.get('pageSize') === '10'
        && requestUrl.searchParams.get('sortBy') === 'id'
        && requestUrl.searchParams.get('sortDirection') === 'desc',
    )

    await page.goto(initialUrl)

    const initialPayload = await readPeoplePayload(await initialResponsePromise)

    expect(initialPayload).toMatchObject({
      page: 3,
      pageSize: 10,
      totalCount: 2500,
      totalPages: 250,
      hasPreviousPage: true,
      hasNextPage: true,
      appliedFilters: {
        search: null,
        location: null,
        role: null,
        sortBy: 'id',
        sortDirection: 'desc',
      },
    })

    await expect(directorySummary(page)).toHaveText('Showing 21-30 of 2500 people')
    await expect(pagerStatus(page)).toHaveText('Page 3 of 250')
    await expect(page.getByLabel('Page size')).toHaveValue('10')
    await expect(page.getByLabel('Sort by')).toHaveValue('id')
    await expect(page.getByLabel('Sort direction')).toHaveValue('desc')
    expect(new URL(page.url()).searchParams.get('page')).toBe('3')

    const filteredResponsePromise = waitForPeopleResponse(
      page,
      (requestUrl) =>
        requestUrl.searchParams.get('search') === 'Mina'
        && requestUrl.searchParams.get('pageSize') === '10'
        && requestUrl.searchParams.get('sortBy') === 'id'
        && requestUrl.searchParams.get('sortDirection') === 'desc'
        && !requestUrl.searchParams.has('page'),
    )
    await page.getByLabel('Search').fill('Mina')

    const filteredPayload = await readPeoplePayload(await filteredResponsePromise)

    expect(filteredPayload).toMatchObject({
      page: 1,
      pageSize: 10,
      totalCount: 1,
      totalPages: 1,
      hasPreviousPage: false,
      hasNextPage: false,
      appliedFilters: {
        search: 'Mina',
        location: null,
        role: null,
        sortBy: 'id',
        sortDirection: 'desc',
      },
    })

    await expect(directorySummary(page)).toHaveText('Showing 1-1 of 1 people')
    await expect(pagerStatus(page)).toHaveText('Page 1 of 1')
    await expect(page.getByRole('heading', { name: 'Mina Patel' })).toBeVisible()
    expect(new URL(page.url()).searchParams.has('page')).toBe(false)

    const resetResponsePromise = waitForPeopleResponse(page, (requestUrl) => requestUrl.search === '')
    await page.getByRole('button', { name: 'Reset view' }).click()

    const resetPayload = await readPeoplePayload(await resetResponsePromise)

    expect(resetPayload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 2500,
      totalPages: 100,
      hasPreviousPage: false,
      hasNextPage: true,
      appliedFilters: {
        search: null,
        location: null,
        role: null,
        sortBy: 'name',
        sortDirection: 'asc',
      },
    })

    await expect(directorySummary(page)).toHaveText(defaultDirectorySummary)
    await expect(pagerStatus(page)).toHaveText(defaultPagerSummary)
    await expect(page.getByLabel('Search')).toHaveValue('')
    await expect(page.getByLabel('Page size')).toHaveValue('25')
    await expect(page.getByRole('button', { name: 'Reset view' })).toBeDisabled()
    expect(new URL(page.url()).search).toBe('')
  })
})