// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'

test.describe('ModernApi people endpoints', () => {
  test('returns the seeded people directory', async ({ request }) => {
    const response = await request.get('/api/people')

    expect(response.ok()).toBeTruthy()

    const people = await response.json()

    expect(Array.isArray(people)).toBe(true)
    expect(people).toHaveLength(5)
    expect(people[0]).toMatchObject({
      id: 1,
      name: 'Mina Patel',
      role: 'Product Strategy Lead',
      location: 'Toronto',
      email: 'mina.patel@example.com',
    })
  })

  test('rejects invalid updates with a validation payload', async ({ request }) => {
    const response = await request.put('/api/people/1', {
      data: {
        name: ' ',
        role: '',
        location: ' ',
        email: '',
      },
    })

    expect(response.status()).toBe(400)

    const payload = await response.json()

    expect(payload.errors.person).toContain(
      'Name, role, location, and email are required.',
    )
  })
})