// Generated by GitHub Copilot
import { expect, type APIResponse, type Locator, type Page } from '@playwright/test'

export interface PersonRecord {
  id: number
  name: string
  role: string
  location: string
  email: string
}

export interface PeoplePagePayload {
  items: PersonRecord[]
  page: number
  pageSize: number
  totalCount: number
  totalPages: number
  hasPreviousPage: boolean
  hasNextPage: boolean
  appliedFilters: {
    search: string | null
    location: string | null
    role: string | null
    sortBy: string
    sortDirection: string
  }
}

export const expectedPeopleEndpoint = `${
  (process.env.PLAYWRIGHT_API_URL ?? 'https://localhost:7114').replace(/\/$/, '')
}/api/people`
export const legacyHostPageUrl = `${(process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:63755').replace(
  /\/$/,
  '',
)}/Default.aspx`
export const modernHostBaseUrl = (process.env.PLAYWRIGHT_MVC_BASE_URL ?? 'https://localhost:7184').replace(
  /\/$/,
  '',
)
export const defaultDirectorySummary = 'Showing 1-25 of 2500 people'
export const defaultPagerSummary = 'Page 1 of 100'
export const restorablePerson2500: PersonRecord = {
  id: 2500,
  name: 'Theo Walker',
  role: 'UX Researcher',
  location: 'Edmonton',
  email: 'theo.walker.2500@example.com',
}

/**
 * Waits for the next GET /api/people response that matches the supplied query predicate.
 * @param {Page} page
 * @param {(requestUrl: URL) => boolean} [predicate]
 * @returns {Promise<APIResponse>}
 */
export async function waitForPeopleResponse(
  page: Page,
  predicate?: (requestUrl: URL) => boolean,
): Promise<APIResponse> {
  return page.waitForResponse((response) => {
    if (response.request().method() !== 'GET') {
      return false
    }

    const requestUrl = new URL(response.url())

    if (requestUrl.pathname !== '/api/people') {
      return false
    }

    return predicate ? predicate(requestUrl) : true
  })
}

/**
 * Reads a people-directory API response into a typed page payload.
 * @param {APIResponse} response
 * @returns {Promise<PeoplePagePayload>}
 */
export async function readPeoplePayload(response: APIResponse): Promise<PeoplePagePayload> {
  expect(response.ok()).toBeTruthy()
  return (await response.json()) as PeoplePagePayload
}

/**
 * Returns the shared people results list for the current host page.
 * @param {Page} page
 * @returns {Locator}
 */
export function peopleList(page: Page): Locator {
  return page.getByRole('list', { name: 'People returned from ModernApi' })
}

/**
 * Returns the live directory summary region for the current page.
 * @param {Page} page
 * @returns {Locator}
 */
export function directorySummary(page: Page): Locator {
  return page.locator('.people-results__summary')
}

/**
 * Returns the pager status text for the current page.
 * @param {Page} page
 * @returns {Locator}
 */
export function pagerStatus(page: Page): Locator {
  return page.getByRole('navigation', { name: 'Directory pages' }).getByRole('status')
}

/**
 * Reads the visible person names from the current people results page.
 * @param {Page} page
 * @returns {Promise<string[]>}
 */
export async function getVisiblePeopleNames(page: Page): Promise<string[]> {
  return peopleList(page).getByRole('heading').allTextContents()
}

/**
 * Verifies the shared React people-directory shell that both hosts render.
 * @param {Page} page
 * @param {string} hostDisplayName
 * @returns {Promise<void>}
 */
export async function expectSharedDirectoryChrome(
  page: Page,
  hostDisplayName: string,
): Promise<void> {
  await expect(page.getByRole('heading', { name: 'People directory' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Who is editing right now' })).toBeVisible()
  await expect(page.locator('.people-hero__summary')).toContainText(
    `This instance is currently hosted by ${hostDisplayName}.`,
  )
  await expect(page.getByRole('region', { name: 'Directory results' })).toContainText(
    expectedPeopleEndpoint,
  )
  await expect(
    page.getByRole('heading', { name: 'Filter, sort, and page the directory' }),
  ).toBeVisible()
  await expect(page.getByRole('searchbox', { name: 'Search' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Location' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Role' })).toBeVisible()
  await expect(page.getByLabel('Sort by')).toBeVisible()
  await expect(page.getByLabel('Sort direction')).toBeVisible()
  await expect(page.getByLabel('Page size')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Reset view' })).toBeVisible()
}