// Generated by GitHub Copilot
import { useEffect, useState } from 'react'
import './App.css'

const peopleEndpointPath = '/api/people'

/**
 * @typedef {Object} Person
 * @property {number} id
 * @property {string} name
 * @property {string} role
 * @property {string} location
 * @property {string} email
 */

/**
 * Builds the people API endpoint for the current host environment.
 * @param {string} apiBaseUrl
 * @returns {string}
 */
function buildPeopleEndpoint(apiBaseUrl) {
  if (!apiBaseUrl) {
    return peopleEndpointPath
  }

  return `${apiBaseUrl.replace(/\/$/, '')}${peopleEndpointPath}`
}

/**
 * Fetches people from the ModernApi service.
 * @param {string} endpoint
 * @param {AbortSignal} signal
 * @returns {Promise<Person[]>}
 */
async function fetchPeople(endpoint, signal) {
  const response = await fetch(endpoint, {
    headers: {
      Accept: 'application/json',
    },
    signal,
  })

  if (!response.ok) {
    throw new Error(`People request failed with status ${response.status}.`)
  }

  return response.json()
}

/**
 * Renders the shared people app backed by ModernApi.
 * @param {{ apiBaseUrl?: string }} props
 * @returns {JSX.Element}
 */
function App({ apiBaseUrl = '' }) {
  const [people, setPeople] = useState([])
  const [requestState, setRequestState] = useState('loading')
  const [errorMessage, setErrorMessage] = useState('')
  const endpoint = buildPeopleEndpoint(apiBaseUrl)

  useEffect(() => {
    const abortController = new AbortController()

    fetchPeople(endpoint, abortController.signal)
      .then((results) => {
        setPeople(results)
        setErrorMessage('')
        setRequestState('loaded')
      })
      .catch((error) => {
        if (error.name === 'AbortError') {
          return
        }

        setPeople([])
        setErrorMessage(error.message)
        setRequestState('error')
      })

    return () => {
      abortController.abort()
    }
  }, [endpoint])

  return (
    <section className="people-app">
      <header className="people-hero">
        <p className="people-hero__eyebrow">ModernApi + React + Web Forms</p>
        <h1>People directory</h1>
        <p className="people-hero__summary">
          The list below is loaded from ModernApi and rendered by the same React
          component in the standalone app and inside LegacyHost.WebForms.
        </p>
      </header>

      <section className="people-surface" aria-labelledby="directory-heading">
        <div className="people-surface__header">
          <div>
            <p className="people-surface__label">Live endpoint</p>
            <p className="people-surface__endpoint">{endpoint}</p>
          </div>
          <div className="people-surface__badge">In-memory data source</div>
        </div>

        <h2 id="directory-heading">Directory results</h2>

        {requestState === 'loading' ? (
          <p className="people-status" role="status" aria-live="polite">
            Loading people...
          </p>
        ) : null}

        {requestState === 'error' ? (
          <p className="people-status people-status--error" role="alert">
            {errorMessage}
          </p>
        ) : null}

        {requestState === 'loaded' && people.length === 0 ? (
          <p className="people-status" role="status" aria-live="polite">
            No people were returned by the API.
          </p>
        ) : null}

        {people.length > 0 ? (
          <ul className="people-grid" aria-label="People returned from ModernApi">
            {people.map((person) => (
              <li className="person-card" key={person.id}>
                <p className="person-card__location">{person.location}</p>
                <h3>{person.name}</h3>
                <p className="person-card__role">{person.role}</p>
                <a href={`mailto:${person.email}`}>{person.email}</a>
              </li>
            ))}
          </ul>
        ) : null}
      </section>
    </section>
  )
}

export default App
