// Generated by GitHub Copilot
import { useEffect, useRef, useState } from 'react'
import './App.css'

const peopleEndpointPath = '/api/people'

/**
 * @typedef {Object} Person
 * @property {number} id
 * @property {string} name
 * @property {string} role
 * @property {string} location
 * @property {string} email
 */

/**
 * Builds an API endpoint for the current host environment.
 * @param {string} apiBaseUrl
 * @param {string} path
 * @returns {string}
 */
function buildApiEndpoint(apiBaseUrl, path) {
  if (!apiBaseUrl) {
    return path
  }

  return `${apiBaseUrl.replace(/\/$/, '')}${path}`
}

/**
 * Fetches people from the ModernApi service.
 * @param {string} endpoint
 * @param {AbortSignal} signal
 * @returns {Promise<Person[]>}
 */
async function fetchPeople(endpoint, signal) {
  const response = await fetch(endpoint, {
    headers: {
      Accept: 'application/json',
    },
    signal,
  })

  if (!response.ok) {
    throw new Error(`People request failed with status ${response.status}.`)
  }

  return response.json()
}

/**
 * Reads an API error payload and returns a readable message.
 * @param {Response} response
 * @returns {Promise<string>}
 */
async function readApiError(response) {
  const payload = await response.json().catch(() => null)

  if (payload?.errors) {
    return Object.values(payload.errors).flat().join(' ')
  }

  if (payload?.title) {
    return payload.title
  }

  return `Request failed with status ${response.status}.`
}

/**
 * Persists an updated person to the ModernApi service.
 * @param {string} endpoint
 * @param {{ name: string, role: string, location: string, email: string }} person
 * @returns {Promise<Person>}
 */
async function updatePerson(endpoint, person) {
  const response = await fetch(endpoint, {
    method: 'PUT',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(person),
  })

  if (!response.ok) {
    throw new Error(await readApiError(response))
  }

  return response.json()
}

/**
 * Creates an editable draft from a person record.
 * @param {Person} person
 * @returns {{ name: string, role: string, location: string, email: string }}
 */
function createPersonDraft(person) {
  return {
    name: person.name,
    role: person.role,
    location: person.location,
    email: person.email,
  }
}

/**
 * Renders an accessible in-page editor for a selected person.
 * @param {{
 *   editingPerson: Person,
 *   formValues: { name: string, role: string, location: string, email: string },
 *   isSaving: boolean,
 *   saveErrorMessage: string,
 *   nameInputRef: import('react').RefObject<HTMLInputElement | null>,
 *   onBackdropClick: (event: import('react').MouseEvent<HTMLDivElement>) => void,
 *   onFieldChange: (event: import('react').ChangeEvent<HTMLInputElement>) => void,
 *   onCancel: () => void,
 *   onSave: () => void,
 * }} props
 * @returns {JSX.Element}
 */
function EditPersonDialog({
  editingPerson,
  formValues,
  isSaving,
  saveErrorMessage,
  nameInputRef,
  onBackdropClick,
  onFieldChange,
  onCancel,
  onSave,
}) {
  return (
    <div className="people-dialog-backdrop" onMouseDown={onBackdropClick}>
      <section
        aria-labelledby="edit-person-heading"
        aria-modal="true"
        className="people-dialog"
        role="dialog"
      >
        <div className="people-dialog__header">
          <div>
            <p className="people-dialog__eyebrow">Edit person</p>
            <h2 id="edit-person-heading">{editingPerson.name}</h2>
            <p className="people-dialog__summary">
              Update this person and save the changes back to the in-memory API.
            </p>
          </div>
          <button
            aria-label="Close edit dialog"
            className="button button--secondary"
            disabled={isSaving}
            onClick={onCancel}
            type="button"
          >
            Close
          </button>
        </div>

        {saveErrorMessage ? (
          <p className="people-status people-status--error" role="alert">
            {saveErrorMessage}
          </p>
        ) : null}

        <div className="people-form-grid">
          <label className="people-field" htmlFor="person-name">
            <span>Name</span>
            <input
              id="person-name"
              name="name"
              onChange={onFieldChange}
              ref={nameInputRef}
              value={formValues.name}
            />
          </label>

          <label className="people-field" htmlFor="person-role">
            <span>Role</span>
            <input
              id="person-role"
              name="role"
              onChange={onFieldChange}
              value={formValues.role}
            />
          </label>

          <label className="people-field" htmlFor="person-location">
            <span>Location</span>
            <input
              id="person-location"
              name="location"
              onChange={onFieldChange}
              value={formValues.location}
            />
          </label>

          <label className="people-field" htmlFor="person-email">
            <span>Email</span>
            <input
              id="person-email"
              name="email"
              onChange={onFieldChange}
              type="email"
              value={formValues.email}
            />
          </label>
        </div>

        <div className="people-form-actions">
          <button
            className="button button--secondary"
            disabled={isSaving}
            onClick={onCancel}
            type="button"
          >
            Cancel
          </button>
          <button
            aria-busy={isSaving}
            className="button"
            disabled={isSaving}
            onClick={onSave}
            type="button"
          >
            {isSaving ? 'Saving...' : 'Save'}
          </button>
        </div>
      </section>
    </div>
  )
}

/**
 * Renders the shared people app backed by ModernApi.
 * @param {{ apiBaseUrl?: string }} props
 * @returns {JSX.Element}
 */
function App({ apiBaseUrl = '' }) {
  const [people, setPeople] = useState([])
  const [requestState, setRequestState] = useState('loading')
  const [errorMessage, setErrorMessage] = useState('')
  const [editingPerson, setEditingPerson] = useState(null)
  const [formValues, setFormValues] = useState({
    name: '',
    role: '',
    location: '',
    email: '',
  })
  const [saveState, setSaveState] = useState('idle')
  const [saveErrorMessage, setSaveErrorMessage] = useState('')
  const nameInputRef = useRef(null)
  const endpoint = buildApiEndpoint(apiBaseUrl, peopleEndpointPath)

  useEffect(() => {
    const abortController = new AbortController()

    fetchPeople(endpoint, abortController.signal)
      .then((results) => {
        setPeople(results)
        setErrorMessage('')
        setRequestState('loaded')
      })
      .catch((error) => {
        if (error.name === 'AbortError') {
          return
        }

        setPeople([])
        setErrorMessage(error.message)
        setRequestState('error')
      })

    return () => {
      abortController.abort()
    }
  }, [endpoint])

  useEffect(() => {
    if (!editingPerson) {
      return undefined
    }

    nameInputRef.current?.focus()

    const handleEscape = (event) => {
      if (event.key === 'Escape' && saveState !== 'saving') {
        setEditingPerson(null)
        setSaveErrorMessage('')
      }
    }

    document.addEventListener('keydown', handleEscape)

    return () => {
      document.removeEventListener('keydown', handleEscape)
    }
  }, [editingPerson, saveState])

  /**
   * Opens the edit dialog for a selected person.
   * @param {Person} person
   * @returns {void}
   */
  function openEditDialog(person) {
    setEditingPerson(person)
    setFormValues(createPersonDraft(person))
    setSaveErrorMessage('')
    setSaveState('idle')
  }

  /**
   * Closes the edit dialog when no save is in progress.
   * @returns {void}
   */
  function closeEditDialog() {
    if (saveState === 'saving') {
      return
    }

    setEditingPerson(null)
    setSaveErrorMessage('')
  }

  /**
   * Updates a single field in the edit dialog.
   * @param {import('react').ChangeEvent<HTMLInputElement>} event
   * @returns {void}
   */
  function handleFieldChange(event) {
    const { name, value } = event.target

    setFormValues((currentValues) => ({
      ...currentValues,
      [name]: value,
    }))
  }

  /**
   * Closes the dialog when the user clicks the backdrop.
   * @param {import('react').MouseEvent<HTMLDivElement>} event
   * @returns {void}
   */
  function handleBackdropClick(event) {
    if (event.target === event.currentTarget) {
      closeEditDialog()
    }
  }

  /**
   * Saves the current dialog values back to the API and local list state.
   * @returns {Promise<void>}
   */
  async function handleSavePerson() {
    if (!editingPerson) {
      return
    }

    const nextValues = {
      name: formValues.name.trim(),
      role: formValues.role.trim(),
      location: formValues.location.trim(),
      email: formValues.email.trim(),
    }

    if (Object.values(nextValues).some((value) => value.length === 0)) {
      setSaveErrorMessage('Name, role, location, and email are required.')
      return
    }

    if (!nextValues.email.includes('@')) {
      setSaveErrorMessage("Email must contain '@'.")
      return
    }

    setSaveState('saving')
    setSaveErrorMessage('')

    try {
      const savedPerson = await updatePerson(
        buildApiEndpoint(apiBaseUrl, `${peopleEndpointPath}/${editingPerson.id}`),
        nextValues,
      )

      setPeople((currentPeople) =>
        currentPeople.map((person) =>
          person.id === savedPerson.id ? savedPerson : person,
        ),
      )
      setEditingPerson(null)
    } catch (error) {
      setSaveErrorMessage(error.message)
    } finally {
      setSaveState('idle')
    }
  }

  return (
    <section className="people-app">
      <header className="people-hero">
        <p className="people-hero__eyebrow">ModernApi + React + Web Forms</p>
        <h1>People directory</h1>
        <p className="people-hero__summary">
          The list below is loaded from ModernApi and rendered by the same React
          component in the standalone app and inside LegacyHost.WebForms.
        </p>
      </header>

      <section className="people-surface" aria-labelledby="directory-heading">
        <div className="people-surface__header">
          <div>
            <p className="people-surface__label">Live endpoint</p>
            <p className="people-surface__endpoint">{endpoint}</p>
          </div>
          <div className="people-surface__badge">In-memory data source</div>
        </div>

        <h2 id="directory-heading">Directory results</h2>

        {requestState === 'loading' ? (
          <p className="people-status" role="status" aria-live="polite">
            Loading people...
          </p>
        ) : null}

        {requestState === 'error' ? (
          <p className="people-status people-status--error" role="alert">
            {errorMessage}
          </p>
        ) : null}

        {requestState === 'loaded' && people.length === 0 ? (
          <p className="people-status" role="status" aria-live="polite">
            No people were returned by the API.
          </p>
        ) : null}

        {people.length > 0 ? (
          <ul className="people-grid" aria-label="People returned from ModernApi">
            {people.map((person) => (
              <li className="person-card" key={person.id}>
                <div className="person-card__header">
                  <p className="person-card__location">{person.location}</p>
                  <button
                    className="person-card__edit"
                    onClick={() => openEditDialog(person)}
                    type="button"
                  >
                    Edit
                  </button>
                </div>
                <h3>{person.name}</h3>
                <p className="person-card__role">{person.role}</p>
                <a href={`mailto:${person.email}`}>{person.email}</a>
              </li>
            ))}
          </ul>
        ) : null}
      </section>

      {editingPerson ? (
        <EditPersonDialog
          editingPerson={editingPerson}
          formValues={formValues}
          isSaving={saveState === 'saving'}
          nameInputRef={nameInputRef}
          onBackdropClick={handleBackdropClick}
          onCancel={closeEditDialog}
          onFieldChange={handleFieldChange}
          onSave={handleSavePerson}
          saveErrorMessage={saveErrorMessage}
        />
      ) : null}
    </section>
  )
}

export default App
