// Generated by GitHub Copilot
import { mountPeopleApp } from './peopleApp.jsx'

const rootElement = document.getElementById('root')

if (rootElement) {
  mountPeopleApp(rootElement, {
    apiBaseUrl:
      rootElement.getAttribute('data-api-base-url') ??
      import.meta.env.VITE_API_BASE_URL ??
      '',
  })
}
