// Generated by GitHub Copilot
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * Normalizes emitted asset names for the embeddable people bundle.
 * @param {{ name?: string }} assetInfo
 * @returns {string}
 */
function getAssetFileName(assetInfo) {
  const name = assetInfo.name ?? ''

  if (name.endsWith('.css')) {
    return 'people-app.css'
  }

  return 'assets/[name][extname]'
}

export default defineConfig({
  define: {
    'process.env.NODE_ENV': JSON.stringify('production'),
  },
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'https://localhost:7114',
        changeOrigin: true,
        secure: false,
      },
    },
  },
  build: {
    copyPublicDir: false,
    cssCodeSplit: false,
    emptyOutDir: true,
    lib: {
      entry: './src/widget.jsx',
      formats: ['es'],
      fileName: () => 'people-app.js',
    },
    rollupOptions: {
      output: {
        assetFileNames: getAssetFileName,
      },
    },
  },
})
