// Generated by GitHub Copilot
namespace ModernHost.Mvc.Models;

/// <summary>
/// Provides the content required by the MVC host landing page.
/// </summary>
public sealed class HomePageViewModel
{
    /// <summary>
    /// Gets the configured base URL for the shared people app backend.
    /// </summary>
    public string PeopleApiBaseUrl { get; init; } = string.Empty;
}