// Generated by GitHub Copilot
import { useEffect, useRef, useState } from 'react'
import './App.css'
import { buildApiEndpoint, createPeoplePresenceConnection } from './peoplePresence.js'

const peopleEndpointPath = '/api/people'
const editorNameStorageKey = 'people-editor-name'

/**
 * @typedef {Object} Person
 * @property {number} id
 * @property {string} name
 * @property {string} role
 * @property {string} location
 * @property {string} email
 */

/**
 * Fetches people from the ModernApi service.
 * @param {string} endpoint
 * @param {AbortSignal} signal
 * @returns {Promise<Person[]>}
 */
async function fetchPeople(endpoint, signal) {
  const response = await fetch(endpoint, {
    headers: {
      Accept: 'application/json',
    },
    signal,
  })

  if (!response.ok) {
    throw new Error(`People request failed with status ${response.status}.`)
  }

  return response.json()
}

/**
 * Reads an API error payload and returns a readable message.
 * @param {Response} response
 * @returns {Promise<string>}
 */
async function readApiError(response) {
  const payload = await response.json().catch(() => null)

  if (payload?.errors) {
    return Object.values(payload.errors).flat().join(' ')
  }

  if (payload?.title) {
    return payload.title
  }

  return `Request failed with status ${response.status}.`
}

/**
 * Persists an updated person to the ModernApi service.
 * @param {string} endpoint
 * @param {{ name: string, role: string, location: string, email: string }} person
 * @returns {Promise<Person>}
 */
async function updatePerson(endpoint, person) {
  const response = await fetch(endpoint, {
    method: 'PUT',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(person),
  })

  if (!response.ok) {
    throw new Error(await readApiError(response))
  }

  return response.json()
}

/**
 * Creates an editable draft from a person record.
 * @param {Person} person
 * @returns {{ name: string, role: string, location: string, email: string }}
 */
function createPersonDraft(person) {
  return {
    name: person.name,
    role: person.role,
    location: person.location,
    email: person.email,
  }
}

/**
 * Creates a readable default editor name for the current browser tab.
 * @returns {string}
 */
function createDefaultEditorName() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return `User ${crypto.randomUUID().slice(0, 8)}`
  }

  return `User ${Math.random().toString(36).slice(2, 10)}`
}

/**
 * Gets the editor name persisted for the current browser tab.
 * @returns {string}
 */
function getInitialEditorName() {
  if (typeof window === 'undefined') {
    return 'Anonymous user'
  }

  const storedName = window.sessionStorage.getItem(editorNameStorageKey)?.trim()

  if (storedName) {
    return storedName
  }

  const defaultName = createDefaultEditorName()
  window.sessionStorage.setItem(editorNameStorageKey, defaultName)
  return defaultName
}

/**
 * Persists the editor name for the current browser tab.
 * @param {string} editorName
 * @returns {void}
 */
function persistEditorName(editorName) {
  if (typeof window !== 'undefined') {
    window.sessionStorage.setItem(editorNameStorageKey, editorName)
  }
}

/**
 * Converts a SignalR presence payload into a person-indexed lookup.
 * @param {{ personId: number, personName: string, editors: string[] }[]} snapshot
 * @returns {Record<number, { personId: number, personName: string, editors: string[] }>}
 */
function normalizePresenceSnapshot(snapshot) {
  return snapshot.reduce((presenceByPersonId, presence) => {
    presenceByPersonId[presence.personId] = presence
    return presenceByPersonId
  }, {})
}

/**
 * Formats editor names for display on cards and summaries.
 * @param {string[]} editorNames
 * @param {string} currentEditorName
 * @returns {string}
 */
function formatEditorNames(editorNames, currentEditorName) {
  return editorNames
    .map((editorName) =>
      editorName === currentEditorName ? 'You' : editorName,
    )
    .join(', ')
}

/**
 * Formats editor names for singular or plural toast copy.
 * @param {string[]} editorNames
 * @param {string} currentEditorName
 * @returns {string}
 */
function formatToastEditorNames(editorNames, currentEditorName) {
  const formattedNames = editorNames.map((editorName) =>
    editorName === currentEditorName ? 'you' : editorName,
  )

  if (formattedNames.length <= 1) {
    return formattedNames[0] ?? ''
  }

  if (formattedNames.length === 2) {
    return `${formattedNames[0]} and ${formattedNames[1]}`
  }

  return `${formattedNames.slice(0, -1).join(', ')}, and ${formattedNames.at(-1)}`
}

/**
 * Announces the current edit state to the SignalR hub.
 * @param {import('@microsoft/signalr').HubConnection} connection
 * @param {{ id: number, name: string } | null} person
 * @param {string} editorName
 * @returns {Promise<void>}
 */
async function syncEditingPresence(connection, person, editorName) {
  if (person) {
    await connection.invoke('StartEditing', {
      personId: person.id,
      personName: person.name,
      editorName,
    })
    return
  }

  await connection.invoke('StopEditing')
}

/**
 * Renders live editing presence and lets the user set a display name.
 * @param {{
 *   editorName: string,
 *   onEditorNameChange: (event: import('react').ChangeEvent<HTMLInputElement>) => void,
 *   presenceState: string,
 *   activeEdits: { personId: number, personName: string, editors: string[] }[],
 *   currentEditorName: string,
 * }} props
 * @returns {JSX.Element}
 */
function EditingPresencePanel({
  editorName,
  onEditorNameChange,
  presenceState,
  activeEdits,
  currentEditorName,
}) {
  const connectionLabelByState = {
    connecting: 'Connecting live presence',
    connected: 'Live presence connected',
    reconnecting: 'Reconnecting live presence',
    disconnected: 'Live presence unavailable',
  }

  return (
    <section aria-labelledby="editing-presence-heading" className="presence-panel">
      <div className="presence-panel__header">
        <div>
          <p className="presence-panel__eyebrow">SignalR presence</p>
          <h2 id="editing-presence-heading">Who is editing right now</h2>
        </div>
        <div className={`presence-panel__status presence-panel__status--${presenceState}`}>
          {connectionLabelByState[presenceState] ?? connectionLabelByState.disconnected}
        </div>
      </div>

      <label className="people-field people-field--presence" htmlFor="editor-name">
        <span>Your display name</span>
        <input
          id="editor-name"
          maxLength="40"
          onChange={onEditorNameChange}
          value={editorName}
        />
      </label>

      {activeEdits.length > 0 ? (
        <ul className="presence-list" aria-label="Active editing presence">
          {activeEdits.map((presence) => (
            <li className="presence-list__item" key={presence.personId}>
              <strong>{formatEditorNames(presence.editors, currentEditorName)}</strong>
              <span> editing {presence.personName}</span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="presence-panel__empty">No one is editing a person right now.</p>
      )}
    </section>
  )
}

/**
 * Renders an accessible in-page editor for a selected person.
 * @param {{
 *   editingPerson: Person,
 *   formValues: { name: string, role: string, location: string, email: string },
 *   isSaving: boolean,
 *   saveErrorMessage: string,
 *   nameInputRef: import('react').RefObject<HTMLInputElement | null>,
 *   onBackdropClick: (event: import('react').MouseEvent<HTMLDivElement>) => void,
 *   onFieldChange: (event: import('react').ChangeEvent<HTMLInputElement>) => void,
 *   onCancel: () => void,
 *   onSave: () => void,
 * }} props
 * @returns {JSX.Element}
 */
function EditPersonDialog({
  editingPerson,
  formValues,
  isSaving,
  otherEditors,
  saveErrorMessage,
  nameInputRef,
  onBackdropClick,
  onFieldChange,
  onCancel,
  onSave,
}) {
  return (
    <div className="people-dialog-backdrop" onMouseDown={onBackdropClick}>
      <section
        aria-labelledby="edit-person-heading"
        aria-modal="true"
        className="people-dialog"
        role="dialog"
      >
        <div className="people-dialog__header">
          <div>
            <p className="people-dialog__eyebrow">Edit person</p>
            <h2 id="edit-person-heading">{editingPerson.name}</h2>
            <p className="people-dialog__summary">
              Update this person and save the changes back to the in-memory API.
            </p>
          </div>
          <button
            aria-label="Close edit dialog"
            className="button button--secondary"
            disabled={isSaving}
            onClick={onCancel}
            type="button"
          >
            Close
          </button>
        </div>

        {saveErrorMessage ? (
          <p className="people-status people-status--error" role="alert">
            {saveErrorMessage}
          </p>
        ) : null}

        {otherEditors.length > 0 ? (
          <p className="people-status" role="status" aria-live="polite">
            Also editing: {otherEditors.join(', ')}
          </p>
        ) : null}

        <div className="people-form-grid">
          <label className="people-field" htmlFor="person-name">
            <span>Name</span>
            <input
              id="person-name"
              name="name"
              onChange={onFieldChange}
              ref={nameInputRef}
              value={formValues.name}
            />
          </label>

          <label className="people-field" htmlFor="person-role">
            <span>Role</span>
            <input
              id="person-role"
              name="role"
              onChange={onFieldChange}
              value={formValues.role}
            />
          </label>

          <label className="people-field" htmlFor="person-location">
            <span>Location</span>
            <input
              id="person-location"
              name="location"
              onChange={onFieldChange}
              value={formValues.location}
            />
          </label>

          <label className="people-field" htmlFor="person-email">
            <span>Email</span>
            <input
              id="person-email"
              name="email"
              onChange={onFieldChange}
              type="email"
              value={formValues.email}
            />
          </label>
        </div>

        <div className="people-form-actions">
          <button
            className="button button--secondary"
            disabled={isSaving}
            onClick={onCancel}
            type="button"
          >
            Cancel
          </button>
          <button
            aria-busy={isSaving}
            className="button"
            disabled={isSaving}
            onClick={onSave}
            type="button"
          >
            {isSaving ? 'Saving...' : 'Save'}
          </button>
        </div>
      </section>
    </div>
  )
}

/**
 * Renders a dismissible toast banner for editing conflicts.
 * @param {{ toast: { id: number, message: string } | null, onDismiss: () => void }} props
 * @returns {JSX.Element | null}
 */
function EditingToast({ toast, onDismiss }) {
  if (!toast) {
    return null
  }

  return (
    <section
      aria-atomic="true"
      aria-live="assertive"
      className="editing-toast"
      role="status"
    >
      <div>
        <p className="editing-toast__eyebrow">Editing alert</p>
        <p className="editing-toast__message">{toast.message}</p>
      </div>
      <button
        aria-label="Dismiss editing alert"
        className="editing-toast__dismiss"
        onClick={onDismiss}
        type="button"
      >
        Dismiss
      </button>
    </section>
  )
}

/**
 * Renders the shared people app backed by ModernApi.
 * @param {{ apiBaseUrl?: string, hostDisplayName?: string }} props
 * @returns {JSX.Element}
 */
function App({ apiBaseUrl = '', hostDisplayName = '' }) {
  const [people, setPeople] = useState([])
  const [requestState, setRequestState] = useState('loading')
  const [errorMessage, setErrorMessage] = useState('')
  const [editingPerson, setEditingPerson] = useState(null)
  const [formValues, setFormValues] = useState({
    name: '',
    role: '',
    location: '',
    email: '',
  })
  const [saveState, setSaveState] = useState('idle')
  const [saveErrorMessage, setSaveErrorMessage] = useState('')
  const [editorName, setEditorName] = useState(() => getInitialEditorName())
  const [presenceState, setPresenceState] = useState('connecting')
  const [editingPresenceByPersonId, setEditingPresenceByPersonId] = useState({})
  const [editingToast, setEditingToast] = useState(null)
  const nameInputRef = useRef(null)
  const connectionRef = useRef(null)
  const editingPersonRef = useRef(null)
  const editorNameRef = useRef('Anonymous user')
  const previousOtherEditorsRef = useRef([])
  const toastTimerRef = useRef(null)
  const currentEditorName = editorName.trim() || 'Anonymous user'
  const endpoint = buildApiEndpoint(apiBaseUrl, peopleEndpointPath)
  const activeEdits = Object.values(editingPresenceByPersonId)
  const resolvedHostDisplayName = hostDisplayName.trim() || 'the current host'
  const otherEditorsForActivePerson = editingPerson
    ? editingPresenceByPersonId[editingPerson.id]?.editors?.filter(
        (editor) => editor !== currentEditorName,
      ) ?? []
    : []

  useEffect(() => {
    editingPersonRef.current = editingPerson
  }, [editingPerson])

  useEffect(() => {
    editorNameRef.current = currentEditorName
  }, [currentEditorName])

  useEffect(() => {
    persistEditorName(currentEditorName)
  }, [currentEditorName])

  useEffect(() => {
    return () => {
      if (toastTimerRef.current !== null) {
        window.clearTimeout(toastTimerRef.current)
      }
    }
  }, [])

  useEffect(() => {
    const abortController = new AbortController()

    fetchPeople(endpoint, abortController.signal)
      .then((results) => {
        setPeople(results)
        setErrorMessage('')
        setRequestState('loaded')
      })
      .catch((error) => {
        if (error.name === 'AbortError') {
          return
        }

        setPeople([])
        setErrorMessage(error.message)
        setRequestState('error')
      })

    return () => {
      abortController.abort()
    }
  }, [endpoint])

  useEffect(() => {
    const connection = createPeoplePresenceConnection(apiBaseUrl)
    connectionRef.current = connection
    let retryTimerId = null
    let isDisposed = false

    connection.on('EditingStateChanged', (snapshot) => {
      setEditingPresenceByPersonId(normalizePresenceSnapshot(snapshot))
    })

    connection.onreconnecting(() => {
      setPresenceState('reconnecting')
    })

    connection.onreconnected(async () => {
      setPresenceState('connected')

      if (editingPersonRef.current) {
        try {
          await syncEditingPresence(
            connection,
            editingPersonRef.current,
            editorNameRef.current,
          )
        } catch {
          setPresenceState('disconnected')
        }
      }
    })

    connection.onclose(() => {
      if (!isDisposed) {
        setPresenceState('disconnected')
      }
    })

    /**
     * Starts the live SignalR connection and retries on startup failure.
     * @returns {Promise<void>}
     */
    async function startConnection() {
      try {
        setPresenceState('connecting')
        await connection.start()

        if (isDisposed) {
          return
        }

        setPresenceState('connected')

        if (editingPersonRef.current) {
          await syncEditingPresence(
            connection,
            editingPersonRef.current,
            editorNameRef.current,
          )
        }
      } catch {
        if (!isDisposed) {
          setPresenceState('disconnected')
          retryTimerId = window.setTimeout(startConnection, 3000)
        }
      }
    }

    startConnection()

    return () => {
      isDisposed = true

      if (retryTimerId !== null) {
        window.clearTimeout(retryTimerId)
      }

      if (connection.state === 'Connected') {
        connection.invoke('StopEditing').catch(() => {})
      }

      connection.stop().catch(() => {})
      connectionRef.current = null
    }
  }, [apiBaseUrl])

  useEffect(() => {
    const connection = connectionRef.current

    if (!connection || presenceState !== 'connected') {
      return
    }

    syncEditingPresence(connection, editingPerson, currentEditorName).catch(() => {
      setPresenceState('disconnected')
    })
  }, [editingPerson, currentEditorName, presenceState])

  useEffect(() => {
    if (!editingPerson) {
      previousOtherEditorsRef.current = []
      return undefined
    }

    nameInputRef.current?.focus()

    const handleEscape = (event) => {
      if (event.key === 'Escape' && saveState !== 'saving') {
        setEditingPerson(null)
        setSaveErrorMessage('')
      }
    }

    document.addEventListener('keydown', handleEscape)

    return () => {
      document.removeEventListener('keydown', handleEscape)
    }
  }, [editingPerson, saveState])

  useEffect(() => {
    if (!editingPerson) {
      previousOtherEditorsRef.current = []
      return
    }

    const previousEditors = new Set(previousOtherEditorsRef.current)
    const addedEditors = otherEditorsForActivePerson.filter(
      (editor) => !previousEditors.has(editor),
    )

    previousOtherEditorsRef.current = otherEditorsForActivePerson

    if (addedEditors.length === 0) {
      return
    }

    const message =
      addedEditors.length === 1
        ? `${formatToastEditorNames(addedEditors, currentEditorName)} also started editing ${editingPerson.name}.`
        : `${formatToastEditorNames(addedEditors, currentEditorName)} also started editing ${editingPerson.name}.`

    const nextToast = {
      id: Date.now(),
      message,
    }

    setEditingToast(nextToast)

    if (toastTimerRef.current !== null) {
      window.clearTimeout(toastTimerRef.current)
    }

    toastTimerRef.current = window.setTimeout(() => {
      setEditingToast((currentToast) =>
        currentToast?.id === nextToast.id ? null : currentToast,
      )
    }, 5000)
  }, [currentEditorName, editingPerson, otherEditorsForActivePerson])

  /**
   * Opens the edit dialog for a selected person.
   * @param {Person} person
   * @returns {void}
   */
  function openEditDialog(person) {
    setEditingPerson(person)
    setFormValues(createPersonDraft(person))
    setSaveErrorMessage('')
    setSaveState('idle')
  }

  /**
   * Closes the edit dialog when no save is in progress.
   * @returns {void}
   */
  function closeEditDialog() {
    if (saveState === 'saving') {
      return
    }

    setEditingPerson(null)
    setSaveErrorMessage('')
  }

  /**
   * Dismisses the active editing toast.
   * @returns {void}
   */
  function dismissEditingToast() {
    if (toastTimerRef.current !== null) {
      window.clearTimeout(toastTimerRef.current)
      toastTimerRef.current = null
    }

    setEditingToast(null)
  }

  /**
   * Updates the current browser-tab display name used for editing presence.
   * @param {import('react').ChangeEvent<HTMLInputElement>} event
   * @returns {void}
   */
  function handleEditorNameChange(event) {
    setEditorName(event.target.value.slice(0, 40))
  }

  /**
   * Updates a single field in the edit dialog.
   * @param {import('react').ChangeEvent<HTMLInputElement>} event
   * @returns {void}
   */
  function handleFieldChange(event) {
    const { name, value } = event.target

    setFormValues((currentValues) => ({
      ...currentValues,
      [name]: value,
    }))
  }

  /**
   * Closes the dialog when the user clicks the backdrop.
   * @param {import('react').MouseEvent<HTMLDivElement>} event
   * @returns {void}
   */
  function handleBackdropClick(event) {
    if (event.target === event.currentTarget) {
      closeEditDialog()
    }
  }

  /**
   * Saves the current dialog values back to the API and local list state.
   * @returns {Promise<void>}
   */
  async function handleSavePerson() {
    if (!editingPerson) {
      return
    }

    const nextValues = {
      name: formValues.name.trim(),
      role: formValues.role.trim(),
      location: formValues.location.trim(),
      email: formValues.email.trim(),
    }

    if (Object.values(nextValues).some((value) => value.length === 0)) {
      setSaveErrorMessage('Name, role, location, and email are required.')
      return
    }

    if (!nextValues.email.includes('@')) {
      setSaveErrorMessage("Email must contain '@'.")
      return
    }

    setSaveState('saving')
    setSaveErrorMessage('')

    try {
      const savedPerson = await updatePerson(
        buildApiEndpoint(apiBaseUrl, `${peopleEndpointPath}/${editingPerson.id}`),
        nextValues,
      )

      setPeople((currentPeople) =>
        currentPeople.map((person) =>
          person.id === savedPerson.id ? savedPerson : person,
        ),
      )
      setEditingPerson(null)
    } catch (error) {
      setSaveErrorMessage(error.message)
    } finally {
      setSaveState('idle')
    }
  }

  return (
    <section className="people-app">
      <EditingToast onDismiss={dismissEditingToast} toast={editingToast} />

      <header className="people-hero">
        <p className="people-hero__eyebrow">ModernApi + React + Shared UI</p>
        <h1>People directory</h1>
        <p className="people-hero__summary">
          The list below is loaded from ModernApi and rendered by the same React
          component in the standalone app and in multiple hosts. This instance is
          currently hosted by <strong>{resolvedHostDisplayName}</strong>.
        </p>
      </header>

      <EditingPresencePanel
        activeEdits={activeEdits}
        currentEditorName={currentEditorName}
        editorName={editorName}
        onEditorNameChange={handleEditorNameChange}
        presenceState={presenceState}
      />

      <section className="people-surface" aria-labelledby="directory-heading">
        <div className="people-surface__header">
          <div>
            <p className="people-surface__label">Live endpoint</p>
            <p className="people-surface__endpoint">{endpoint}</p>
          </div>
          <div className="people-surface__badge">In-memory data source</div>
        </div>

        <h2 id="directory-heading">Directory results</h2>

        {requestState === 'loading' ? (
          <p className="people-status" role="status" aria-live="polite">
            Loading people...
          </p>
        ) : null}

        {requestState === 'error' ? (
          <p className="people-status people-status--error" role="alert">
            {errorMessage}
          </p>
        ) : null}

        {requestState === 'loaded' && people.length === 0 ? (
          <p className="people-status" role="status" aria-live="polite">
            No people were returned by the API.
          </p>
        ) : null}

        {people.length > 0 ? (
          <ul className="people-grid" aria-label="People returned from ModernApi">
            {people.map((person) => (
              <li className="person-card" key={person.id}>
                {editingPresenceByPersonId[person.id]?.editors?.length ? (
                  <p className="person-card__presence" role="status" aria-live="polite">
                    {formatEditorNames(
                      editingPresenceByPersonId[person.id].editors,
                      currentEditorName,
                    )}{' '}
                    editing now
                  </p>
                ) : null}
                <div className="person-card__header">
                  <p className="person-card__location">{person.location}</p>
                  <button
                    className="person-card__edit"
                    onClick={() => openEditDialog(person)}
                    type="button"
                  >
                    Edit
                  </button>
                </div>
                <h3>{person.name}</h3>
                <p className="person-card__role">{person.role}</p>
                <a href={`mailto:${person.email}`}>{person.email}</a>
              </li>
            ))}
          </ul>
        ) : null}
      </section>

      {editingPerson ? (
        <EditPersonDialog
          editingPerson={editingPerson}
          formValues={formValues}
          isSaving={saveState === 'saving'}
          nameInputRef={nameInputRef}
          otherEditors={otherEditorsForActivePerson}
          onBackdropClick={handleBackdropClick}
          onCancel={closeEditDialog}
          onFieldChange={handleFieldChange}
          onSave={handleSavePerson}
          saveErrorMessage={saveErrorMessage}
        />
      ) : null}
    </section>
  )
}

export default App
