// Generated by GitHub Copilot
import { useEffect, useRef, useState } from 'react'
import './App.css'
import { buildApiEndpoint, createPeoplePresenceConnection } from './peoplePresence.js'

const peopleEndpointPath = '/api/people'
const editorNameStorageKey = 'people-editor-name'
const defaultQueryState = Object.freeze({
  page: 1,
  pageSize: 25,
  search: '',
  location: '',
  role: '',
  sortBy: 'name',
  sortDirection: 'asc',
})
const pageSizeOptions = Object.freeze([10, 25, 50, 100])
const sortFieldOptions = Object.freeze([
  { value: 'name', label: 'Name' },
  { value: 'id', label: 'ID' },
  { value: 'location', label: 'Location' },
  { value: 'role', label: 'Role' },
  { value: 'email', label: 'Email' },
])
const sortDirectionOptions = Object.freeze([
  { value: 'asc', label: 'Ascending' },
  { value: 'desc', label: 'Descending' },
])
const supportedSortFields = new Set(
  sortFieldOptions.map((option) => option.value),
)

/**
 * @typedef {Object} Person
 * @property {number} id
 * @property {string} name
 * @property {string} role
 * @property {string} location
 * @property {string} email
 */

/**
 * @typedef {Object} DirectoryQuery
 * @property {number} page
 * @property {number} pageSize
 * @property {string} search
 * @property {string} location
 * @property {string} role
 * @property {string} sortBy
 * @property {string} sortDirection
 */

/**
 * @typedef {Object} PeoplePage
 * @property {Person[]} items
 * @property {number} page
 * @property {number} pageSize
 * @property {number} totalCount
 * @property {number} totalPages
 * @property {boolean} hasPreviousPage
 * @property {boolean} hasNextPage
 * @property {{ search: string | null, location: string | null, role: string | null, sortBy: string, sortDirection: string }} appliedFilters
 */

/**
 * Fetches a single paged directory envelope from the ModernApi service.
 * @param {string} requestUrl
 * @param {AbortSignal} signal
 * @returns {Promise<PeoplePage>}
 */
async function fetchPeoplePage(requestUrl, signal) {
  const response = await fetch(requestUrl, {
    headers: {
      Accept: 'application/json',
    },
    signal,
  })

  if (!response.ok) {
    throw new Error(`People request failed with status ${response.status}.`)
  }

  return response.json()
}

/**
 * Trims a query-string filter value and converts blank values into an empty string.
 * @param {string | null | undefined} value
 * @returns {string}
 */
function normalizeFilterValue(value) {
  return typeof value === 'string' ? value.trim() : ''
}

/**
 * Normalizes a 1-based page number to a valid positive integer.
 * @param {number | string | null | undefined} value
 * @returns {number}
 */
function normalizePageValue(value) {
  const parsedValue = Number.parseInt(String(value ?? ''), 10)

  return Number.isFinite(parsedValue) && parsedValue > 0
    ? parsedValue
    : defaultQueryState.page
}

/**
 * Normalizes page size values to the supported API range.
 * @param {number | string | null | undefined} value
 * @returns {number}
 */
function normalizePageSizeValue(value) {
  const parsedValue = Number.parseInt(String(value ?? ''), 10)

  if (!Number.isFinite(parsedValue) || parsedValue <= 0) {
    return defaultQueryState.pageSize
  }

  return Math.min(parsedValue, 100)
}

/**
 * Normalizes the requested sort field to the server contract.
 * @param {string | null | undefined} value
 * @returns {string}
 */
function normalizeSortBy(value) {
  const normalizedValue = normalizeFilterValue(value).toLowerCase()

  return supportedSortFields.has(normalizedValue)
    ? normalizedValue
    : defaultQueryState.sortBy
}

/**
 * Normalizes the requested sort direction to ascending or descending.
 * @param {string | null | undefined} value
 * @returns {string}
 */
function normalizeSortDirection(value) {
  return normalizeFilterValue(value).toLowerCase() === 'desc'
    ? 'desc'
    : defaultQueryState.sortDirection
}

/**
 * Produces a fully normalized directory query state object.
 * @param {Partial<DirectoryQuery>} [queryState]
 * @returns {DirectoryQuery}
 */
function normalizeQueryState(queryState = defaultQueryState) {
  return {
    page: normalizePageValue(queryState.page),
    pageSize: normalizePageSizeValue(queryState.pageSize),
    search: normalizeFilterValue(queryState.search),
    location: normalizeFilterValue(queryState.location),
    role: normalizeFilterValue(queryState.role),
    sortBy: normalizeSortBy(queryState.sortBy),
    sortDirection: normalizeSortDirection(queryState.sortDirection),
  }
}

/**
 * Reads the browser URL query string into normalized directory state.
 * @returns {DirectoryQuery}
 */
function readQueryFromUrl() {
  if (typeof window === 'undefined') {
    return { ...defaultQueryState }
  }

  const searchParams = new URLSearchParams(window.location.search)

  return normalizeQueryState({
    page: searchParams.get('page'),
    pageSize: searchParams.get('pageSize'),
    search: searchParams.get('search'),
    location: searchParams.get('location'),
    role: searchParams.get('role'),
    sortBy: searchParams.get('sortBy'),
    sortDirection: searchParams.get('sortDirection'),
  })
}

/**
 * Converts the current query state into a stable browser query string.
 * @param {DirectoryQuery} queryState
 * @returns {string}
 */
function buildQueryString(queryState) {
  const normalizedQueryState = normalizeQueryState(queryState)
  const searchParams = new URLSearchParams()

  if (normalizedQueryState.search) {
    searchParams.set('search', normalizedQueryState.search)
  }

  if (normalizedQueryState.location) {
    searchParams.set('location', normalizedQueryState.location)
  }

  if (normalizedQueryState.role) {
    searchParams.set('role', normalizedQueryState.role)
  }

  if (normalizedQueryState.sortBy !== defaultQueryState.sortBy) {
    searchParams.set('sortBy', normalizedQueryState.sortBy)
  }

  if (normalizedQueryState.sortDirection !== defaultQueryState.sortDirection) {
    searchParams.set('sortDirection', normalizedQueryState.sortDirection)
  }

  if (normalizedQueryState.pageSize !== defaultQueryState.pageSize) {
    searchParams.set('pageSize', String(normalizedQueryState.pageSize))
  }

  if (normalizedQueryState.page !== defaultQueryState.page) {
    searchParams.set('page', String(normalizedQueryState.page))
  }

  return searchParams.toString()
}

/**
 * Builds the GET /api/people request URL for the active query state.
 * @param {string} endpoint
 * @param {DirectoryQuery} queryState
 * @returns {string}
 */
function buildPeopleRequestUrl(endpoint, queryState) {
  const queryString = buildQueryString(queryState)
  return queryString ? `${endpoint}?${queryString}` : endpoint
}

/**
 * Compares two query-state objects after normalization.
 * @param {DirectoryQuery} leftQueryState
 * @param {DirectoryQuery} rightQueryState
 * @returns {boolean}
 */
function sameQueryState(leftQueryState, rightQueryState) {
  const normalizedLeftQueryState = normalizeQueryState(leftQueryState)
  const normalizedRightQueryState = normalizeQueryState(rightQueryState)

  return (
    normalizedLeftQueryState.page === normalizedRightQueryState.page
    && normalizedLeftQueryState.pageSize === normalizedRightQueryState.pageSize
    && normalizedLeftQueryState.search === normalizedRightQueryState.search
    && normalizedLeftQueryState.location === normalizedRightQueryState.location
    && normalizedLeftQueryState.role === normalizedRightQueryState.role
    && normalizedLeftQueryState.sortBy === normalizedRightQueryState.sortBy
    && normalizedLeftQueryState.sortDirection
      === normalizedRightQueryState.sortDirection
  )
}

/**
 * Creates an empty page envelope for loading and error states.
 * @param {DirectoryQuery} [queryState]
 * @returns {PeoplePage}
 */
function createEmptyDirectoryPage(queryState = defaultQueryState) {
  const normalizedQueryState = normalizeQueryState(queryState)

  return {
    items: [],
    page: normalizedQueryState.page,
    pageSize: normalizedQueryState.pageSize,
    totalCount: 0,
    totalPages: 0,
    hasPreviousPage: false,
    hasNextPage: false,
    appliedFilters: {
      search: normalizedQueryState.search || null,
      location: normalizedQueryState.location || null,
      role: normalizedQueryState.role || null,
      sortBy: normalizedQueryState.sortBy,
      sortDirection: normalizedQueryState.sortDirection,
    },
  }
}

/**
 * Checks whether a saved person still belongs in the currently filtered view.
 * @param {Person} person
 * @param {DirectoryQuery} queryState
 * @returns {boolean}
 */
function matchesActiveFilters(person, queryState) {
  const normalizedQueryState = normalizeQueryState(queryState)
  const normalizedSearch = normalizedQueryState.search.toLowerCase()

  if (normalizedSearch) {
    const matchesSearch = [person.name, person.role, person.location, person.email]
      .some((value) => value.toLowerCase().includes(normalizedSearch))

    if (!matchesSearch) {
      return false
    }
  }

  if (
    normalizedQueryState.location
    && person.location.toLowerCase() !== normalizedQueryState.location.toLowerCase()
  ) {
    return false
  }

  if (
    normalizedQueryState.role
    && person.role.toLowerCase() !== normalizedQueryState.role.toLowerCase()
  ) {
    return false
  }

  return true
}

/**
 * Calculates the current result range for the loaded page envelope.
 * @param {PeoplePage} directoryPage
 * @returns {{ start: number, end: number }}
 */
function getResultRange(directoryPage) {
  if (directoryPage.totalCount === 0 || directoryPage.items.length === 0) {
    return { start: 0, end: 0 }
  }

  const start = (directoryPage.page - 1) * directoryPage.pageSize + 1
  const end = start + directoryPage.items.length - 1
  return { start, end }
}

/**
 * Formats a readable result summary using the current page metadata.
 * @param {PeoplePage} directoryPage
 * @returns {string}
 */
function formatDirectorySummary(directoryPage) {
  if (directoryPage.totalCount === 0) {
    return 'Showing 0 results'
  }

  if (directoryPage.items.length === 0) {
    return `Showing 0 results on page ${directoryPage.page} of ${directoryPage.totalPages}`
  }

  const resultRange = getResultRange(directoryPage)
  return `Showing ${resultRange.start}-${resultRange.end} of ${directoryPage.totalCount} people`
}

/**
 * Determines whether the current query differs from the default directory view.
 * @param {DirectoryQuery} queryState
 * @returns {boolean}
 */
function hasCustomQueryState(queryState) {
  return !sameQueryState(queryState, defaultQueryState)
}

/**
 * Reads an API error payload and returns a readable message.
 * @param {Response} response
 * @returns {Promise<string>}
 */
async function readApiError(response) {
  const payload = await response.json().catch(() => null)

  if (payload?.errors) {
    return Object.values(payload.errors).flat().join(' ')
  }

  if (payload?.title) {
    return payload.title
  }

  return `Request failed with status ${response.status}.`
}

/**
 * Persists an updated person to the ModernApi service.
 * @param {string} endpoint
 * @param {{ name: string, role: string, location: string, email: string }} person
 * @returns {Promise<Person>}
 */
async function updatePerson(endpoint, person) {
  const response = await fetch(endpoint, {
    method: 'PUT',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(person),
  })

  if (!response.ok) {
    throw new Error(await readApiError(response))
  }

  return response.json()
}

/**
 * Creates an editable draft from a person record.
 * @param {Person} person
 * @returns {{ name: string, role: string, location: string, email: string }}
 */
function createPersonDraft(person) {
  return {
    name: person.name,
    role: person.role,
    location: person.location,
    email: person.email,
  }
}

/**
 * Creates a readable default editor name for the current browser tab.
 * @returns {string}
 */
function createDefaultEditorName() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return `User ${crypto.randomUUID().slice(0, 8)}`
  }

  return `User ${Math.random().toString(36).slice(2, 10)}`
}

/**
 * Gets the editor name persisted for the current browser tab.
 * @returns {string}
 */
function getInitialEditorName() {
  if (typeof window === 'undefined') {
    return 'Anonymous user'
  }

  const storedName = window.sessionStorage.getItem(editorNameStorageKey)?.trim()

  if (storedName) {
    return storedName
  }

  const defaultName = createDefaultEditorName()
  window.sessionStorage.setItem(editorNameStorageKey, defaultName)
  return defaultName
}

/**
 * Persists the editor name for the current browser tab.
 * @param {string} editorName
 * @returns {void}
 */
function persistEditorName(editorName) {
  if (typeof window !== 'undefined') {
    window.sessionStorage.setItem(editorNameStorageKey, editorName)
  }
}

/**
 * Converts a SignalR presence payload into a person-indexed lookup.
 * @param {{ personId: number, personName: string, editors: string[] }[]} snapshot
 * @returns {Record<number, { personId: number, personName: string, editors: string[] }>}
 */
function normalizePresenceSnapshot(snapshot) {
  return snapshot.reduce((presenceByPersonId, presence) => {
    presenceByPersonId[presence.personId] = presence
    return presenceByPersonId
  }, {})
}

/**
 * Formats editor names for display on cards and summaries.
 * @param {string[]} editorNames
 * @param {string} currentEditorName
 * @returns {string}
 */
function formatEditorNames(editorNames, currentEditorName) {
  return editorNames
    .map((editorName) =>
      editorName === currentEditorName ? 'You' : editorName,
    )
    .join(', ')
}

/**
 * Formats editor names for singular or plural toast copy.
 * @param {string[]} editorNames
 * @param {string} currentEditorName
 * @returns {string}
 */
function formatToastEditorNames(editorNames, currentEditorName) {
  const formattedNames = editorNames.map((editorName) =>
    editorName === currentEditorName ? 'you' : editorName,
  )

  if (formattedNames.length <= 1) {
    return formattedNames[0] ?? ''
  }

  if (formattedNames.length === 2) {
    return `${formattedNames[0]} and ${formattedNames[1]}`
  }

  return `${formattedNames.slice(0, -1).join(', ')}, and ${formattedNames.at(-1)}`
}

/**
 * Announces the current edit state to the SignalR hub.
 * @param {import('@microsoft/signalr').HubConnection} connection
 * @param {{ id: number, name: string } | null} person
 * @param {string} editorName
 * @returns {Promise<void>}
 */
async function syncEditingPresence(connection, person, editorName) {
  if (person) {
    await connection.invoke('StartEditing', {
      personId: person.id,
      personName: person.name,
      editorName,
    })
    return
  }

  await connection.invoke('StopEditing')
}

/**
 * Renders live editing presence and lets the user set a display name.
 * @param {{
 *   editorName: string,
 *   onEditorNameChange: (event: import('react').ChangeEvent<HTMLInputElement>) => void,
 *   presenceState: string,
 *   activeEdits: { personId: number, personName: string, editors: string[] }[],
 *   currentEditorName: string,
 * }} props
 * @returns {JSX.Element}
 */
function EditingPresencePanel({
  editorName,
  onEditorNameChange,
  presenceState,
  activeEdits,
  currentEditorName,
}) {
  const connectionLabelByState = {
    connecting: 'Connecting live presence',
    connected: 'Live presence connected',
    reconnecting: 'Reconnecting live presence',
    disconnected: 'Live presence unavailable',
  }

  return (
    <section aria-labelledby="editing-presence-heading" className="presence-panel">
      <div className="presence-panel__header">
        <div>
          <p className="presence-panel__eyebrow">SignalR presence</p>
          <h2 id="editing-presence-heading">Who is editing right now</h2>
        </div>
        <div className={`presence-panel__status presence-panel__status--${presenceState}`}>
          {connectionLabelByState[presenceState] ?? connectionLabelByState.disconnected}
        </div>
      </div>

      <label className="people-field people-field--presence" htmlFor="editor-name">
        <span>Your display name</span>
        <input
          id="editor-name"
          maxLength="40"
          onChange={onEditorNameChange}
          value={editorName}
        />
      </label>

      {activeEdits.length > 0 ? (
        <ul className="presence-list" aria-label="Active editing presence">
          {activeEdits.map((presence) => (
            <li className="presence-list__item" key={presence.personId}>
              <strong>{formatEditorNames(presence.editors, currentEditorName)}</strong>
              <span> editing {presence.personName}</span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="presence-panel__empty">No one is editing a person right now.</p>
      )}
    </section>
  )
}

/**
 * Renders accessible filtering, sorting, and page-size controls.
 * @param {{
 *   queryState: DirectoryQuery,
 *   pageSizeChoices: number[],
 *   isResetEnabled: boolean,
 *   onQueryInputChange: (event: import('react').ChangeEvent<HTMLInputElement>) => void,
 *   onSortByChange: (event: import('react').ChangeEvent<HTMLSelectElement>) => void,
 *   onSortDirectionChange: (event: import('react').ChangeEvent<HTMLSelectElement>) => void,
 *   onPageSizeChange: (event: import('react').ChangeEvent<HTMLSelectElement>) => void,
 *   onReset: () => void,
 * }} props
 * @returns {JSX.Element}
 */
function FilterControls({
  queryState,
  pageSizeChoices,
  isResetEnabled,
  onQueryInputChange,
  onSortByChange,
  onSortDirectionChange,
  onPageSizeChange,
  onReset,
}) {
  return (
    <section aria-labelledby="directory-controls-heading" className="directory-toolbar">
      <div className="directory-toolbar__header">
        <div>
          <p className="directory-toolbar__eyebrow">Directory controls</p>
          <h3 id="directory-controls-heading">Filter, sort, and page the directory</h3>
          <p className="directory-toolbar__summary">
            Search across names, roles, locations, and email, then move through
            the server-side result pages.
          </p>
        </div>
        <div className="directory-toolbar__actions">
          <button
            className="button button--secondary directory-toolbar__reset"
            disabled={!isResetEnabled}
            onClick={onReset}
            type="button"
          >
            Reset view
          </button>
        </div>
      </div>

      <div className="directory-toolbar__grid">
        <label className="people-field" htmlFor="directory-search">
          <span>Search</span>
          <input
            id="directory-search"
            name="search"
            onChange={onQueryInputChange}
            type="search"
            value={queryState.search}
          />
        </label>

        <label className="people-field" htmlFor="directory-location">
          <span>Location</span>
          <input
            id="directory-location"
            name="location"
            onChange={onQueryInputChange}
            value={queryState.location}
          />
        </label>

        <label className="people-field" htmlFor="directory-role">
          <span>Role</span>
          <input
            id="directory-role"
            name="role"
            onChange={onQueryInputChange}
            value={queryState.role}
          />
        </label>

        <label className="people-field" htmlFor="directory-sort-by">
          <span>Sort by</span>
          <select id="directory-sort-by" onChange={onSortByChange} value={queryState.sortBy}>
            {sortFieldOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </label>

        <label className="people-field" htmlFor="directory-sort-direction">
          <span>Sort direction</span>
          <select
            id="directory-sort-direction"
            onChange={onSortDirectionChange}
            value={queryState.sortDirection}
          >
            {sortDirectionOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </label>

        <label className="people-field" htmlFor="directory-page-size">
          <span>Page size</span>
          <select id="directory-page-size" onChange={onPageSizeChange} value={queryState.pageSize}>
            {pageSizeChoices.map((pageSize) => (
              <option key={pageSize} value={pageSize}>
                {pageSize} per page
              </option>
            ))}
          </select>
        </label>
      </div>
    </section>
  )
}

/**
 * Renders accessible pager controls for the active result set.
 * @param {{
 *   page: number,
 *   totalPages: number,
 *   hasPreviousPage: boolean,
 *   hasNextPage: boolean,
 *   onPageChange: (page: number) => void,
 * }} props
 * @returns {JSX.Element | null}
 */
function PagerControls({
  page,
  totalPages,
  hasPreviousPage,
  hasNextPage,
  onPageChange,
}) {
  if (totalPages === 0) {
    return null
  }

  return (
    <nav aria-label="Directory pages" className="people-pager">
      <p className="people-pager__meta" role="status" aria-live="polite">
        Page {page} of {totalPages}
      </p>

      <div className="people-pager__buttons">
        <button
          className="people-pager__button"
          disabled={!hasPreviousPage}
          onClick={() => onPageChange(1)}
          type="button"
        >
          First
        </button>
        <button
          className="people-pager__button"
          disabled={!hasPreviousPage}
          onClick={() => onPageChange(page - 1)}
          type="button"
        >
          Previous
        </button>
        <button
          className="people-pager__button"
          disabled={!hasNextPage}
          onClick={() => onPageChange(page + 1)}
          type="button"
        >
          Next
        </button>
        <button
          className="people-pager__button"
          disabled={!hasNextPage}
          onClick={() => onPageChange(totalPages)}
          type="button"
        >
          Last
        </button>
      </div>
    </nav>
  )
}

/**
 * Renders an accessible in-page editor for a selected person.
 * @param {{
 *   editingPerson: Person,
 *   formValues: { name: string, role: string, location: string, email: string },
 *   isSaving: boolean,
 *   otherEditors: string[],
 *   saveErrorMessage: string,
 *   nameInputRef: import('react').RefObject<HTMLInputElement | null>,
 *   onBackdropClick: (event: import('react').MouseEvent<HTMLDivElement>) => void,
 *   onFieldChange: (event: import('react').ChangeEvent<HTMLInputElement>) => void,
 *   onCancel: () => void,
 *   onSave: () => void,
 * }} props
 * @returns {JSX.Element}
 */
function EditPersonDialog({
  editingPerson,
  formValues,
  isSaving,
  otherEditors,
  saveErrorMessage,
  nameInputRef,
  onBackdropClick,
  onFieldChange,
  onCancel,
  onSave,
}) {
  return (
    <div className="people-dialog-backdrop" onMouseDown={onBackdropClick}>
      <section
        aria-labelledby="edit-person-heading"
        aria-modal="true"
        className="people-dialog"
        role="dialog"
      >
        <div className="people-dialog__header">
          <div>
            <p className="people-dialog__eyebrow">Edit person</p>
            <h2 id="edit-person-heading">{editingPerson.name}</h2>
            <p className="people-dialog__summary">
              Update this person and save the changes back to the in-memory API.
            </p>
          </div>
          <button
            aria-label="Close edit dialog"
            className="button button--secondary"
            disabled={isSaving}
            onClick={onCancel}
            type="button"
          >
            Close
          </button>
        </div>

        {saveErrorMessage ? (
          <p className="people-status people-status--error" role="alert">
            {saveErrorMessage}
          </p>
        ) : null}

        {otherEditors.length > 0 ? (
          <p className="people-status" role="status" aria-live="polite">
            Also editing: {otherEditors.join(', ')}
          </p>
        ) : null}

        <div className="people-form-grid">
          <label className="people-field" htmlFor="person-name">
            <span>Name</span>
            <input
              id="person-name"
              name="name"
              onChange={onFieldChange}
              ref={nameInputRef}
              value={formValues.name}
            />
          </label>

          <label className="people-field" htmlFor="person-role">
            <span>Role</span>
            <input
              id="person-role"
              name="role"
              onChange={onFieldChange}
              value={formValues.role}
            />
          </label>

          <label className="people-field" htmlFor="person-location">
            <span>Location</span>
            <input
              id="person-location"
              name="location"
              onChange={onFieldChange}
              value={formValues.location}
            />
          </label>

          <label className="people-field" htmlFor="person-email">
            <span>Email</span>
            <input
              id="person-email"
              name="email"
              onChange={onFieldChange}
              type="email"
              value={formValues.email}
            />
          </label>
        </div>

        <div className="people-form-actions">
          <button
            className="button button--secondary"
            disabled={isSaving}
            onClick={onCancel}
            type="button"
          >
            Cancel
          </button>
          <button
            aria-busy={isSaving}
            className="button"
            disabled={isSaving}
            onClick={onSave}
            type="button"
          >
            {isSaving ? 'Saving...' : 'Save'}
          </button>
        </div>
      </section>
    </div>
  )
}

/**
 * Renders a dismissible toast banner for editing conflicts.
 * @param {{ toast: { id: number, message: string } | null, onDismiss: () => void }} props
 * @returns {JSX.Element | null}
 */
function EditingToast({ toast, onDismiss }) {
  if (!toast) {
    return null
  }

  return (
    <section
      aria-atomic="true"
      aria-live="assertive"
      className="editing-toast"
      role="status"
    >
      <div>
        <p className="editing-toast__eyebrow">Editing alert</p>
        <p className="editing-toast__message">{toast.message}</p>
      </div>
      <button
        aria-label="Dismiss editing alert"
        className="editing-toast__dismiss"
        onClick={onDismiss}
        type="button"
      >
        Dismiss
      </button>
    </section>
  )
}

/**
 * Renders the shared people app backed by ModernApi.
 * @param {{ apiBaseUrl?: string, hostDisplayName?: string }} props
 * @returns {JSX.Element}
 */
function App({ apiBaseUrl = '', hostDisplayName = '' }) {
  const [queryState, setQueryState] = useState(() => readQueryFromUrl())
  const [directoryPage, setDirectoryPage] = useState(() => createEmptyDirectoryPage())
  const [requestState, setRequestState] = useState('loading')
  const [reloadVersion, setReloadVersion] = useState(0)
  const [errorMessage, setErrorMessage] = useState('')
  const [editingPerson, setEditingPerson] = useState(null)
  const [formValues, setFormValues] = useState({
    name: '',
    role: '',
    location: '',
    email: '',
  })
  const [saveState, setSaveState] = useState('idle')
  const [saveErrorMessage, setSaveErrorMessage] = useState('')
  const [editorName, setEditorName] = useState(() => getInitialEditorName())
  const [presenceState, setPresenceState] = useState('connecting')
  const [editingPresenceByPersonId, setEditingPresenceByPersonId] = useState({})
  const [editingToast, setEditingToast] = useState(null)
  const nameInputRef = useRef(null)
  const connectionRef = useRef(null)
  const editingPersonRef = useRef(null)
  const editorNameRef = useRef('Anonymous user')
  const previousOtherEditorsRef = useRef([])
  const toastTimerRef = useRef(null)
  const currentEditorName = editorName.trim() || 'Anonymous user'
  const endpoint = buildApiEndpoint(apiBaseUrl, peopleEndpointPath)
  const peopleRequestUrl = buildPeopleRequestUrl(endpoint, queryState)
  const activeEdits = Object.values(editingPresenceByPersonId)
  const people = directoryPage.items
  const resolvedHostDisplayName = hostDisplayName.trim() || 'the current host'
  const pageSizeChoices = pageSizeOptions.includes(queryState.pageSize)
    ? pageSizeOptions
    : [...pageSizeOptions, queryState.pageSize].sort((left, right) => left - right)
  const otherEditorsForActivePerson = editingPerson
    ? editingPresenceByPersonId[editingPerson.id]?.editors?.filter(
        (editor) => editor !== currentEditorName,
      ) ?? []
    : []
  const currentQueryString = buildQueryString(queryState)
  const emptyStateMessage =
    directoryPage.totalCount === 0
      ? 'No people match the current query.'
      : 'This page has no results. Try a different page or adjust the current filters.'

  useEffect(() => {
    editingPersonRef.current = editingPerson
  }, [editingPerson])

  useEffect(() => {
    editorNameRef.current = currentEditorName
  }, [currentEditorName])

  useEffect(() => {
    persistEditorName(currentEditorName)
  }, [currentEditorName])

  useEffect(() => {
    return () => {
      if (toastTimerRef.current !== null) {
        window.clearTimeout(toastTimerRef.current)
      }
    }
  }, [])

  useEffect(() => {
    if (typeof window === 'undefined') {
      return
    }

    const currentSearch = window.location.search.startsWith('?')
      ? window.location.search.slice(1)
      : window.location.search

    if (currentSearch === currentQueryString) {
      return
    }

    const nextUrl = `${window.location.pathname}${currentQueryString ? `?${currentQueryString}` : ''}${window.location.hash}`
    window.history.pushState({ directoryQuery: currentQueryString }, '', nextUrl)
  }, [currentQueryString])

  useEffect(() => {
    if (typeof window === 'undefined') {
      return undefined
    }

    /**
     * Syncs the browser back-forward stack into React query state.
     * @returns {void}
     */
    function handlePopState() {
      const nextQueryState = readQueryFromUrl()

      setQueryState((currentQueryState) =>
        sameQueryState(currentQueryState, nextQueryState)
          ? currentQueryState
          : nextQueryState,
      )
    }

    window.addEventListener('popstate', handlePopState)

    return () => {
      window.removeEventListener('popstate', handlePopState)
    }
  }, [])

  useEffect(() => {
    const abortController = new AbortController()
    const requestedQueryState = queryState

    setRequestState('loading')
    setErrorMessage('')
    setDirectoryPage(createEmptyDirectoryPage(requestedQueryState))

    fetchPeoplePage(peopleRequestUrl, abortController.signal)
      .then((pageEnvelope) => {
        setDirectoryPage(pageEnvelope)
        setRequestState('loaded')
      })
      .catch((error) => {
        if (error.name === 'AbortError') {
          return
        }

        setDirectoryPage(createEmptyDirectoryPage(requestedQueryState))
        setErrorMessage(error.message)
        setRequestState('error')
      })

    return () => {
      abortController.abort()
    }
  }, [peopleRequestUrl, queryState, reloadVersion])

  useEffect(() => {
    const connection = createPeoplePresenceConnection(apiBaseUrl)
    connectionRef.current = connection
    let retryTimerId = null
    let isDisposed = false

    connection.on('EditingStateChanged', (snapshot) => {
      setEditingPresenceByPersonId(normalizePresenceSnapshot(snapshot))
    })

    connection.onreconnecting(() => {
      setPresenceState('reconnecting')
    })

    connection.onreconnected(async () => {
      setPresenceState('connected')

      if (editingPersonRef.current) {
        try {
          await syncEditingPresence(
            connection,
            editingPersonRef.current,
            editorNameRef.current,
          )
        } catch {
          setPresenceState('disconnected')
        }
      }
    })

    connection.onclose(() => {
      if (!isDisposed) {
        setPresenceState('disconnected')
      }
    })

    /**
     * Starts the live SignalR connection and retries on startup failure.
     * @returns {Promise<void>}
     */
    async function startConnection() {
      try {
        setPresenceState('connecting')
        await connection.start()

        if (isDisposed) {
          return
        }

        setPresenceState('connected')

        if (editingPersonRef.current) {
          await syncEditingPresence(
            connection,
            editingPersonRef.current,
            editorNameRef.current,
          )
        }
      } catch {
        if (!isDisposed) {
          setPresenceState('disconnected')
          retryTimerId = window.setTimeout(startConnection, 3000)
        }
      }
    }

    startConnection()

    return () => {
      isDisposed = true

      if (retryTimerId !== null) {
        window.clearTimeout(retryTimerId)
      }

      if (connection.state === 'Connected') {
        connection.invoke('StopEditing').catch(() => {})
      }

      connection.stop().catch(() => {})
      connectionRef.current = null
    }
  }, [apiBaseUrl])

  useEffect(() => {
    const connection = connectionRef.current

    if (!connection || presenceState !== 'connected') {
      return
    }

    syncEditingPresence(connection, editingPerson, currentEditorName).catch(() => {
      setPresenceState('disconnected')
    })
  }, [editingPerson, currentEditorName, presenceState])

  useEffect(() => {
    if (!editingPerson) {
      previousOtherEditorsRef.current = []
      return undefined
    }

    nameInputRef.current?.focus()

    const handleEscape = (event) => {
      if (event.key === 'Escape' && saveState !== 'saving') {
        setEditingPerson(null)
        setSaveErrorMessage('')
      }
    }

    document.addEventListener('keydown', handleEscape)

    return () => {
      document.removeEventListener('keydown', handleEscape)
    }
  }, [editingPerson, saveState])

  useEffect(() => {
    if (!editingPerson) {
      previousOtherEditorsRef.current = []
      return
    }

    const previousEditors = new Set(previousOtherEditorsRef.current)
    const addedEditors = otherEditorsForActivePerson.filter(
      (editor) => !previousEditors.has(editor),
    )

    previousOtherEditorsRef.current = otherEditorsForActivePerson

    if (addedEditors.length === 0) {
      return
    }

    const nextToast = {
      id: Date.now(),
      message: `${formatToastEditorNames(addedEditors, currentEditorName)} also started editing ${editingPerson.name}.`,
    }

    setEditingToast(nextToast)

    if (toastTimerRef.current !== null) {
      window.clearTimeout(toastTimerRef.current)
    }

    toastTimerRef.current = window.setTimeout(() => {
      setEditingToast((currentToast) =>
        currentToast?.id === nextToast.id ? null : currentToast,
      )
    }, 5000)
  }, [currentEditorName, editingPerson, otherEditorsForActivePerson])

  /**
   * Applies a partial query-state update and resets paging when required.
   * @param {Partial<DirectoryQuery>} nextQueryState
   * @param {boolean} shouldResetPage
   * @returns {void}
   */
  function updateQueryState(nextQueryState, shouldResetPage = false) {
    setQueryState((currentQueryState) => {
      const normalizedNextQueryState = normalizeQueryState({
        ...currentQueryState,
        ...nextQueryState,
        page: shouldResetPage
          ? 1
          : nextQueryState.page ?? currentQueryState.page,
      })

      return sameQueryState(currentQueryState, normalizedNextQueryState)
        ? currentQueryState
        : normalizedNextQueryState
    })
  }

  /**
   * Opens the edit dialog for a selected person.
   * @param {Person} person
   * @returns {void}
   */
  function openEditDialog(person) {
    setEditingPerson(person)
    setFormValues(createPersonDraft(person))
    setSaveErrorMessage('')
    setSaveState('idle')
  }

  /**
   * Closes the edit dialog when no save is in progress.
   * @returns {void}
   */
  function closeEditDialog() {
    if (saveState === 'saving') {
      return
    }

    setEditingPerson(null)
    setSaveErrorMessage('')
  }

  /**
   * Dismisses the active editing toast.
   * @returns {void}
   */
  function dismissEditingToast() {
    if (toastTimerRef.current !== null) {
      window.clearTimeout(toastTimerRef.current)
      toastTimerRef.current = null
    }

    setEditingToast(null)
  }

  /**
   * Updates the current browser-tab display name used for editing presence.
   * @param {import('react').ChangeEvent<HTMLInputElement>} event
   * @returns {void}
   */
  function handleEditorNameChange(event) {
    setEditorName(event.target.value.slice(0, 40))
  }

  /**
   * Updates the text-based search and filter inputs.
   * @param {import('react').ChangeEvent<HTMLInputElement>} event
   * @returns {void}
   */
  function handleQueryInputChange(event) {
    const { name, value } = event.target
    updateQueryState({ [name]: value }, true)
  }

  /**
   * Updates the selected sort field.
   * @param {import('react').ChangeEvent<HTMLSelectElement>} event
   * @returns {void}
   */
  function handleSortByChange(event) {
    updateQueryState({ sortBy: event.target.value }, true)
  }

  /**
   * Updates the selected sort direction.
   * @param {import('react').ChangeEvent<HTMLSelectElement>} event
   * @returns {void}
   */
  function handleSortDirectionChange(event) {
    updateQueryState({ sortDirection: event.target.value }, true)
  }

  /**
   * Updates the selected page size.
   * @param {import('react').ChangeEvent<HTMLSelectElement>} event
   * @returns {void}
   */
  function handlePageSizeChange(event) {
    updateQueryState({ pageSize: event.target.value }, true)
  }

  /**
   * Moves the directory to a new page.
   * @param {number} page
   * @returns {void}
   */
  function handlePageChange(page) {
    updateQueryState({ page })
  }

  /**
   * Resets the directory query back to the default view.
   * @returns {void}
   */
  function handleResetQueryState() {
    setQueryState((currentQueryState) =>
      sameQueryState(currentQueryState, defaultQueryState)
        ? currentQueryState
        : { ...defaultQueryState },
    )
  }

  /**
   * Updates a single field in the edit dialog.
   * @param {import('react').ChangeEvent<HTMLInputElement>} event
   * @returns {void}
   */
  function handleFieldChange(event) {
    const { name, value } = event.target

    setFormValues((currentValues) => ({
      ...currentValues,
      [name]: value,
    }))
  }

  /**
   * Closes the dialog when the user clicks the backdrop.
   * @param {import('react').MouseEvent<HTMLDivElement>} event
   * @returns {void}
   */
  function handleBackdropClick(event) {
    if (event.target === event.currentTarget) {
      closeEditDialog()
    }
  }

  /**
   * Saves the current dialog values back to the API and current directory page.
   * @returns {Promise<void>}
   */
  async function handleSavePerson() {
    if (!editingPerson) {
      return
    }

    const nextValues = {
      name: formValues.name.trim(),
      role: formValues.role.trim(),
      location: formValues.location.trim(),
      email: formValues.email.trim(),
    }

    if (Object.values(nextValues).some((value) => value.length === 0)) {
      setSaveErrorMessage('Name, role, location, and email are required.')
      return
    }

    if (!nextValues.email.includes('@')) {
      setSaveErrorMessage("Email must contain '@'.")
      return
    }

    setSaveState('saving')
    setSaveErrorMessage('')

    try {
      const savedPerson = await updatePerson(
        buildApiEndpoint(apiBaseUrl, `${peopleEndpointPath}/${editingPerson.id}`),
        nextValues,
      )

      if (matchesActiveFilters(savedPerson, queryState)) {
        setDirectoryPage((currentDirectoryPage) => ({
          ...currentDirectoryPage,
          items: currentDirectoryPage.items.map((person) =>
            person.id === savedPerson.id ? savedPerson : person,
          ),
        }))
      } else {
        setReloadVersion((currentVersion) => currentVersion + 1)
      }

      setEditingPerson(null)
    } catch (error) {
      setSaveErrorMessage(error.message)
    } finally {
      setSaveState('idle')
    }
  }

  return (
    <section className="people-app">
      <EditingToast onDismiss={dismissEditingToast} toast={editingToast} />

      <header className="people-hero">
        <p className="people-hero__eyebrow">ModernApi + React + Shared UI</p>
        <h1>People directory</h1>
        <p className="people-hero__summary">
          The list below is loaded from ModernApi and rendered by the same React
          component in the standalone app and in multiple hosts. This instance is
          currently hosted by <strong>{resolvedHostDisplayName}</strong>.
        </p>
      </header>

      <EditingPresencePanel
        activeEdits={activeEdits}
        currentEditorName={currentEditorName}
        editorName={editorName}
        onEditorNameChange={handleEditorNameChange}
        presenceState={presenceState}
      />

      <section
        aria-busy={requestState === 'loading'}
        aria-labelledby="directory-heading"
        className="people-surface"
      >
        <div className="people-surface__header">
          <div>
            <p className="people-surface__label">Live endpoint</p>
            <p className="people-surface__endpoint">{endpoint}</p>
          </div>
          <div className="people-surface__badge">In-memory data source</div>
        </div>

        <h2 id="directory-heading">Directory results</h2>

        <FilterControls
          isResetEnabled={hasCustomQueryState(queryState)}
          onPageSizeChange={handlePageSizeChange}
          onQueryInputChange={handleQueryInputChange}
          onReset={handleResetQueryState}
          onSortByChange={handleSortByChange}
          onSortDirectionChange={handleSortDirectionChange}
          pageSizeChoices={pageSizeChoices}
          queryState={queryState}
        />

        {requestState === 'loading' ? (
          <p className="people-status" role="status" aria-live="polite">
            Loading people...
          </p>
        ) : null}

        {requestState === 'error' ? (
          <p className="people-status people-status--error" role="alert">
            {errorMessage}
          </p>
        ) : null}

        {requestState === 'loaded' ? (
          <p className="people-results__summary" role="status" aria-live="polite">
            {formatDirectorySummary(directoryPage)}
          </p>
        ) : null}

        {requestState === 'loaded' && people.length === 0 ? (
          <p className="people-status" role="status" aria-live="polite">
            {emptyStateMessage}
          </p>
        ) : null}

        {requestState === 'loaded' && people.length > 0 ? (
          <ul className="people-grid" aria-label="People returned from ModernApi">
            {people.map((person) => (
              <li className="person-card" key={person.id}>
                {editingPresenceByPersonId[person.id]?.editors?.length ? (
                  <p className="person-card__presence" role="status" aria-live="polite">
                    {formatEditorNames(
                      editingPresenceByPersonId[person.id].editors,
                      currentEditorName,
                    )}{' '}
                    editing now
                  </p>
                ) : null}
                <div className="person-card__header">
                  <p className="person-card__location">{person.location}</p>
                  <button
                    className="person-card__edit"
                    onClick={() => openEditDialog(person)}
                    type="button"
                  >
                    Edit
                  </button>
                </div>
                <h3>{person.name}</h3>
                <p className="person-card__role">{person.role}</p>
                <a href={`mailto:${person.email}`}>{person.email}</a>
              </li>
            ))}
          </ul>
        ) : null}

        {requestState === 'loaded' ? (
          <PagerControls
            hasNextPage={directoryPage.hasNextPage}
            hasPreviousPage={directoryPage.hasPreviousPage}
            onPageChange={handlePageChange}
            page={directoryPage.page}
            totalPages={directoryPage.totalPages}
          />
        ) : null}
      </section>

      {editingPerson ? (
        <EditPersonDialog
          editingPerson={editingPerson}
          formValues={formValues}
          isSaving={saveState === 'saving'}
          nameInputRef={nameInputRef}
          otherEditors={otherEditorsForActivePerson}
          onBackdropClick={handleBackdropClick}
          onCancel={closeEditDialog}
          onFieldChange={handleFieldChange}
          onSave={handleSavePerson}
          saveErrorMessage={saveErrorMessage}
        />
      ) : null}
    </section>
  )
}

export default App
