// Generated by GitHub Copilot
import { HubConnectionBuilder, LogLevel } from '@microsoft/signalr'

const editingHubPath = '/hubs/peopleEditing'

/**
 * Builds an API-relative or absolute endpoint path.
 * @param {string} apiBaseUrl
 * @param {string} path
 * @returns {string}
 */
export function buildApiEndpoint(apiBaseUrl, path) {
  if (!apiBaseUrl) {
    return path
  }

  return `${apiBaseUrl.replace(/\/$/, '')}${path}`
}

/**
 * Creates a SignalR connection for live people-editing presence updates.
 * @param {string} apiBaseUrl
 * @returns {import('@microsoft/signalr').HubConnection}
 */
export function createPeoplePresenceConnection(apiBaseUrl) {
  return new HubConnectionBuilder()
    .withUrl(buildApiEndpoint(apiBaseUrl, editingHubPath), {
      withCredentials: false,
    })
    .withAutomaticReconnect()
    .configureLogging(LogLevel.Warning)
    .build()
}