// Generated by GitHub Copilot
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'

/**
 * Mounts the shared people app into a specific DOM element.
 * @param {Element} container
 * @param {{ apiBaseUrl?: string, hostDisplayName?: string }} [options]
 * @returns {void}
 */
export function mountPeopleApp(container, options = {}) {
  const root = createRoot(container)

  root.render(
    <StrictMode>
      <App
        apiBaseUrl={
          options.apiBaseUrl ?? container.getAttribute('data-api-base-url') ?? ''
        }
        hostDisplayName={
          options.hostDisplayName ??
          container.getAttribute('data-host-display-name') ??
          ''
        }
      />
    </StrictMode>,
  )
}

/**
 * Mounts the shared people app into any legacy host placeholders on the page.
 * @param {string} [selector]
 * @returns {void}
 */
export function autoMountPeopleApps(selector = '[data-people-app]') {
  document.querySelectorAll(selector).forEach((container) => {
    if (container.getAttribute('data-people-mounted') === 'true') {
      return
    }

    container.setAttribute('data-people-mounted', 'true')
    mountPeopleApp(container)
  })
}