// Generated by GitHub Copilot
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("LegacyHost.WebForms")]
[assembly: AssemblyDescription("Legacy ASP.NET Web Forms host for the solution.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("LegacyHost.WebForms")]
[assembly: ComVisible(false)]
[assembly: Guid("FDF5CF4A-A789-4BDD-8319-F9A3958B6412")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]