// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'
import {
  directorySummary,
  legacyHostPageUrl,
  modernHostBaseUrl,
  peopleList,
  readPeoplePayload,
  waitForPeopleResponse,
} from './people-directory-test-helpers'

test.describe('Shared people app across hosts', () => {
  test('uses the same paged contract in both hosts and shares live editing presence', async ({
    context,
    page,
  }) => {
    const modernHostPage = await context.newPage()
    const sharedQuery = '?search=Mina&pageSize=10'
    const sharedRequest = (requestUrl: URL) =>
      requestUrl.searchParams.get('search') === 'Mina'
      && requestUrl.searchParams.get('pageSize') === '10'
      && !requestUrl.searchParams.has('page')

    try {
      const legacyResponsePromise = waitForPeopleResponse(page, sharedRequest)
      const modernResponsePromise = waitForPeopleResponse(modernHostPage, sharedRequest)

      await Promise.all([
        page.goto(`${legacyHostPageUrl}${sharedQuery}`),
        modernHostPage.goto(`${modernHostBaseUrl}${sharedQuery}`),
      ])

      const [legacyPayload, modernPayload] = await Promise.all([
        readPeoplePayload(await legacyResponsePromise),
        readPeoplePayload(await modernResponsePromise),
      ])

      expect(legacyPayload).toEqual(modernPayload)
      expect(legacyPayload).toMatchObject({
        page: 1,
        pageSize: 10,
        totalCount: 1,
        totalPages: 1,
        hasPreviousPage: false,
        hasNextPage: false,
        appliedFilters: {
          search: 'Mina',
          location: null,
          role: null,
          sortBy: 'name',
          sortDirection: 'asc',
        },
      })

      await expect(page.locator('.people-hero__summary')).toContainText(
        'This instance is currently hosted by LegacyHost.WebForms.',
      )
      await expect(modernHostPage.locator('.people-hero__summary')).toContainText(
        'This instance is currently hosted by ModernHost.Mvc.',
      )
      await expect(directorySummary(page)).toHaveText('Showing 1-1 of 1 people')
      await expect(directorySummary(modernHostPage)).toHaveText('Showing 1-1 of 1 people')
      await expect(peopleList(page).getByRole('listitem')).toHaveCount(1)
      await expect(peopleList(modernHostPage).getByRole('listitem')).toHaveCount(1)

      await expect(page.getByText('Live presence connected')).toBeVisible()
      await expect(modernHostPage.getByText('Live presence connected')).toBeVisible()

      await page.getByLabel('Your display name').fill('Legacy Host Editor')
      await modernHostPage.getByLabel('Your display name').fill('Modern Host Observer')

      const legacyMinaCard = peopleList(page).getByRole('listitem').first()

      await legacyMinaCard.getByRole('button', { name: 'Edit' }).click()
      await expect(page.getByRole('dialog', { name: 'Mina Patel' })).toBeVisible()
      await expect(
        modernHostPage.getByRole('list', {
          name: 'Active editing presence',
        }),
      ).toContainText('Legacy Host Editor editing Mina Patel')
      await expect(peopleList(modernHostPage).getByRole('listitem').first()).toContainText(
        'Legacy Host Editor editing now',
      )

      await page.getByRole('button', { name: 'Cancel' }).click()
      await expect(page.getByRole('dialog', { name: 'Mina Patel' })).toBeHidden()
      await expect(modernHostPage.getByText('No one is editing a person right now.')).toBeVisible()
    } finally {
      await modernHostPage.close()
    }
  })
})