// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'
import { restorablePerson2500 } from './people-directory-test-helpers'

test.describe('ModernApi people endpoints', () => {
  test('returns a paged directory envelope by default', async ({ request }) => {
    const response = await request.get('/api/people')

    expect(response.ok()).toBeTruthy()

    const payload = await response.json()

    expect(payload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 2500,
      totalPages: 100,
      hasPreviousPage: false,
      hasNextPage: true,
      appliedFilters: {
        search: null,
        location: null,
        role: null,
        sortBy: 'name',
        sortDirection: 'asc',
      },
    })

    expect(Array.isArray(payload.items)).toBe(true)
    expect(payload.items).toHaveLength(25)
  })

  test('applies deterministic sorting and paging on the server', async ({ request }) => {
    const response = await request.get('/api/people', {
      params: {
        page: '2',
        pageSize: '3',
        sortBy: 'id',
        sortDirection: 'desc',
      },
    })

    expect(response.ok()).toBeTruthy()

    const payload = await response.json()

    expect(payload).toMatchObject({
      page: 2,
      pageSize: 3,
      totalCount: 2500,
      totalPages: 834,
      hasPreviousPage: true,
      hasNextPage: true,
      appliedFilters: {
        search: null,
        location: null,
        role: null,
        sortBy: 'id',
        sortDirection: 'desc',
      },
    })

    expect(payload.items.map((person) => person.id)).toEqual([2497, 2496, 2495])
  })

  test('uses id as the stable secondary key for grouped sorts', async ({ request }) => {
    const response = await request.get('/api/people', {
      params: {
        page: '1',
        pageSize: '5',
        sortBy: 'location',
        sortDirection: 'asc',
      },
    })

    expect(response.ok()).toBeTruthy()

    const payload = await response.json()

    expect(payload.appliedFilters).toMatchObject({
      sortBy: 'location',
      sortDirection: 'asc',
    })

    expect(payload.items.map((person) => person.id)).toEqual([4, 36, 37, 38, 39])
    expect(payload.items.every((person) => person.location === 'Calgary')).toBe(true)
  })

  test('filters the directory and clamps invalid query inputs predictably', async ({ request }) => {
    const response = await request.get('/api/people', {
      params: {
        page: '-8',
        pageSize: '999',
        search: '  Mina  ',
        location: ' Toronto ',
        role: 'Product Strategy Lead',
        sortBy: 'unsupported',
        sortDirection: 'sideways',
      },
    })

    expect(response.ok()).toBeTruthy()

    const payload = await response.json()

    expect(payload).toMatchObject({
      page: 1,
      pageSize: 100,
      totalCount: 1,
      totalPages: 1,
      hasPreviousPage: false,
      hasNextPage: false,
      appliedFilters: {
        search: 'Mina',
        location: 'Toronto',
        role: 'Product Strategy Lead',
        sortBy: 'name',
        sortDirection: 'asc',
      },
    })

    expect(payload.items).toEqual([
      {
        id: 1,
        name: 'Mina Patel',
        role: 'Product Strategy Lead',
        location: 'Toronto',
        email: 'mina.patel@example.com',
      },
    ])
  })

  test('keeps paging metadata consistent for combined role and location filters', async ({ request }) => {
    const response = await request.get('/api/people', {
      params: {
        page: '2',
        pageSize: '2',
        location: 'Toronto',
        role: 'Platform Engineer',
        sortBy: 'id',
      },
    })

    expect(response.ok()).toBeTruthy()

    const payload = await response.json()

    expect(payload).toMatchObject({
      page: 2,
      pageSize: 2,
      totalCount: 21,
      totalPages: 11,
      hasPreviousPage: true,
      hasNextPage: true,
      appliedFilters: {
        search: null,
        location: 'Toronto',
        role: 'Platform Engineer',
        sortBy: 'id',
        sortDirection: 'asc',
      },
    })

    expect(payload.items.map((person) => person.id)).toEqual([246, 366])
    expect(payload.items.every((person) => person.location === 'Toronto')).toBe(true)
    expect(payload.items.every((person) => person.role === 'Platform Engineer')).toBe(true)
  })

  test('returns an empty page envelope when filters match nothing', async ({ request }) => {
    const response = await request.get('/api/people', {
      params: {
        search: 'no-such-person',
      },
    })

    expect(response.ok()).toBeTruthy()

    const payload = await response.json()

    expect(payload).toMatchObject({
      page: 1,
      pageSize: 25,
      totalCount: 0,
      totalPages: 0,
      hasPreviousPage: false,
      hasNextPage: false,
      appliedFilters: {
        search: 'no-such-person',
        location: null,
        role: null,
        sortBy: 'name',
        sortDirection: 'asc',
      },
    })

    expect(payload.items).toEqual([])
  })

  test('keeps person updates working with the paged contract', async ({ request }) => {
    const updatedPersonPayload = {
      ...restorablePerson2500,
      name: 'Theo Walker Updated',
      role: 'Principal UX Researcher',
    }

    try {
      const response = await request.put('/api/people/2500', {
        data: updatedPersonPayload,
      })

      expect(response.ok()).toBeTruthy()

      const updatedPerson = await response.json()

      expect(updatedPerson).toMatchObject(updatedPersonPayload)

      const lookupResponse = await request.get('/api/people', {
        params: {
          search: updatedPersonPayload.name,
        },
      })

      expect(lookupResponse.ok()).toBeTruthy()

      const payload = await lookupResponse.json()

      expect(payload.totalCount).toBe(1)
      expect(payload.items[0]).toMatchObject({
        id: restorablePerson2500.id,
        name: updatedPersonPayload.name,
      })
    } finally {
      const restoreResponse = await request.put('/api/people/2500', {
        data: restorablePerson2500,
      })

      expect(restoreResponse.ok()).toBeTruthy()
    }
  })

  test('rejects invalid updates with a validation payload', async ({ request }) => {
    const response = await request.put('/api/people/1', {
      data: {
        name: ' ',
        role: '',
        location: ' ',
        email: '',
      },
    })

    expect(response.status()).toBe(400)

    const payload = await response.json()

    expect(payload.errors.person).toContain(
      'Name, role, location, and email are required.',
    )
  })
})