// Generated by GitHub Copilot
import { expect, test } from '@playwright/test'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { legacyHostPageUrl, modernHostBaseUrl } from './people-directory-test-helpers'

const currentDirectory = path.dirname(fileURLToPath(import.meta.url))
const screenshotDirectory = path.resolve(currentDirectory, '..', 'test-results', 'captures')

test.describe('Side-by-side mixed host screenshots', () => {
  test('captures both hosts while live editing presence is active', async ({ page }, testInfo) => {
    test.setTimeout(60_000)

    const sharedQuery = '?search=Mina&pageSize=10'
    const loadedScreenshotPath = path.join(
      screenshotDirectory,
      'mixed-host-side-by-side-loaded.png',
    )
    const editingScreenshotPath = path.join(
      screenshotDirectory,
      'mixed-host-side-by-side-left-editing.png',
    )
    const dualEditingScreenshotPath = path.join(
      screenshotDirectory,
      'mixed-host-side-by-side-dual-editing.png',
    )

    await fs.mkdir(screenshotDirectory, { recursive: true })
    await page.setViewportSize({ width: 2200, height: 1500 })
    await page.setContent(`
      <!doctype html>
      <html lang="en">
        <head>
          <meta charset="utf-8" />
          <title>Mixed Host Presence Capture</title>
          <style>
            :root {
              color-scheme: light;
              font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
              background:
                radial-gradient(circle at top left, rgba(13, 110, 253, 0.16), transparent 28%),
                linear-gradient(180deg, #f4f7fb 0%, #e6edf6 100%);
              color: #11243d;
            }

            * {
              box-sizing: border-box;
            }

            body {
              margin: 0;
            }

            main {
              min-height: 100vh;
              padding: 28px;
            }

            header {
              margin-bottom: 20px;
              padding: 24px 28px;
              border: 1px solid rgba(17, 36, 61, 0.08);
              border-radius: 24px;
              background: rgba(255, 255, 255, 0.9);
              box-shadow: 0 20px 45px rgba(17, 36, 61, 0.08);
            }

            h1 {
              margin: 0 0 8px;
              font-size: 2rem;
              line-height: 1.1;
            }

            p {
              margin: 0;
              font-size: 1rem;
              color: #38506f;
            }

            section {
              display: grid;
              grid-template-columns: repeat(2, minmax(0, 1fr));
              gap: 20px;
            }

            figure {
              margin: 0;
              border: 1px solid rgba(17, 36, 61, 0.08);
              border-radius: 24px;
              overflow: hidden;
              background: rgba(255, 255, 255, 0.96);
              box-shadow: 0 20px 45px rgba(17, 36, 61, 0.08);
            }

            figcaption {
              padding: 14px 18px;
              font-size: 0.95rem;
              font-weight: 700;
              letter-spacing: 0.02em;
              color: #183a63;
              background: linear-gradient(90deg, rgba(13, 110, 253, 0.12), rgba(32, 201, 151, 0.12));
              border-bottom: 1px solid rgba(17, 36, 61, 0.08);
            }

            iframe {
              display: block;
              width: 100%;
              height: 1320px;
              border: 0;
              background: #ffffff;
            }
          </style>
        </head>
        <body>
          <main>
            <header>
              <h1>Shared live editing presence across both hosts</h1>
              <p>LegacyHost.WebForms is shown on the left and ModernHost.Mvc is shown on the right.</p>
            </header>
            <section aria-label="Comparison layout">
              <figure>
                <figcaption>LegacyHost.WebForms</figcaption>
                <iframe
                  title="LegacyHost.WebForms"
                  src="${legacyHostPageUrl}${sharedQuery}"></iframe>
              </figure>
              <figure>
                <figcaption>ModernHost.Mvc</figcaption>
                <iframe
                  title="ModernHost.Mvc"
                  src="${modernHostBaseUrl}${sharedQuery}"></iframe>
              </figure>
            </section>
          </main>
        </body>
      </html>
    `)

    const legacyFrame = page.frameLocator('iframe[title="LegacyHost.WebForms"]')
    const modernFrame = page.frameLocator('iframe[title="ModernHost.Mvc"]')

    await expect(legacyFrame.getByRole('heading', { name: 'People directory' })).toBeVisible()
    await expect(modernFrame.getByRole('heading', { name: 'People directory' })).toBeVisible()
    await expect(legacyFrame.locator('.people-hero__summary')).toContainText(
      'This instance is currently hosted by LegacyHost.WebForms.',
    )
    await expect(modernFrame.locator('.people-hero__summary')).toContainText(
      'This instance is currently hosted by ModernHost.Mvc.',
    )

    await legacyFrame.getByLabel('Your display name').fill('Legacy Host Editor')
    await modernFrame.getByLabel('Your display name').fill('Modern Host Observer')

    await page.screenshot({ path: loadedScreenshotPath, fullPage: true })
    await testInfo.attach('side-by-side-loaded', {
      path: loadedScreenshotPath,
      contentType: 'image/png',
    })

    await legacyFrame.getByRole('button', { name: 'Edit' }).click()
    await expect(legacyFrame.getByRole('dialog', { name: 'Mina Patel' })).toBeVisible()
    await expect(
      modernFrame.getByRole('list', { name: 'Active editing presence' }),
    ).toContainText('Legacy Host Editor editing Mina Patel')
    await expect(modernFrame.locator('.person-card').filter({ hasText: 'Mina Patel' })).toContainText(
      'Legacy Host Editor editing now',
    )

    await page.screenshot({ path: editingScreenshotPath, fullPage: true })
    await testInfo.attach('side-by-side-left-editing', {
      path: editingScreenshotPath,
      contentType: 'image/png',
    })

    await modernFrame.getByRole('button', { name: 'Edit' }).click()
    await expect(modernFrame.getByRole('dialog', { name: 'Mina Patel' })).toBeVisible()
    await expect(legacyFrame.getByText('Also editing: Modern Host Observer')).toBeVisible()
    await expect(modernFrame.getByText('Also editing: Legacy Host Editor')).toBeVisible()

    await page.screenshot({ path: dualEditingScreenshotPath, fullPage: true })
    await testInfo.attach('side-by-side-dual-editing', {
      path: dualEditingScreenshotPath,
      contentType: 'image/png',
    })

    await modernFrame.getByRole('button', { name: 'Cancel' }).click()
    await expect(modernFrame.getByRole('dialog', { name: 'Mina Patel' })).toBeHidden()
    await expect(legacyFrame.getByText('Also editing: Modern Host Observer')).toBeHidden()

    await legacyFrame.getByRole('button', { name: 'Cancel' }).click()
    await expect(legacyFrame.getByRole('dialog', { name: 'Mina Patel' })).toBeHidden()
    await expect(modernFrame.getByText('No one is editing a person right now.')).toBeVisible()
  })
})