using ModernApi.People;
using ModernApi.PeopleEditing;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

// Generated by GitHub Copilot
builder.Services.AddCors(options =>
{
    options.AddPolicy("LocalClientApps", policy =>
    {
        policy
            .SetIsOriginAllowed(static origin =>
                Uri.TryCreate(origin, UriKind.Absolute, out var uri)
                && (uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase)
                    || uri.Host.Equals("127.0.0.1", StringComparison.OrdinalIgnoreCase)))
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});
builder.Services.AddSignalR();
builder.Services.AddSingleton<PeopleDirectoryService>();
builder.Services.AddSingleton<PeopleEditingTracker>();
builder.Services.AddOpenApi();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();
app.UseCors("LocalClientApps");

app.MapGet("/api/people", ([AsParameters] PeopleQueryRequest request, PeopleDirectoryService peopleDirectory) =>
{
    return TypedResults.Ok(peopleDirectory.GetPeoplePage(request));
})
    .WithName("GetPeople");

app.MapPut("/api/people/{id:int}", (int id, UpdatePersonRequest request, PeopleDirectoryService peopleDirectory) =>
{
    if (string.IsNullOrWhiteSpace(request.Name)
        || string.IsNullOrWhiteSpace(request.Role)
        || string.IsNullOrWhiteSpace(request.Location)
        || string.IsNullOrWhiteSpace(request.Email))
    {
        return Results.ValidationProblem(new Dictionary<string, string[]>
        {
            ["person"] = ["Name, role, location, and email are required."]
        });
    }

    if (!request.Email.Contains('@'))
    {
        return Results.ValidationProblem(new Dictionary<string, string[]>
        {
            ["email"] = ["Email must contain '@'."]
        });
    }

    var updatedPerson = peopleDirectory.UpdatePerson(id, request);
    return updatedPerson is null ? Results.NotFound() : Results.Ok(updatedPerson);
})
    .WithName("UpdatePerson");

app.MapHub<PeopleEditingHub>("/hubs/peopleEditing");

app.Run();
