using ModernApi.PeopleEditing;

var builder = WebApplication.CreateBuilder(args);

// Generated by GitHub Copilot
builder.Services.AddCors(options =>
{
    options.AddPolicy("LocalClientApps", policy =>
    {
        policy
            .SetIsOriginAllowed(static origin =>
                Uri.TryCreate(origin, UriKind.Absolute, out var uri)
                && (uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase)
                    || uri.Host.Equals("127.0.0.1", StringComparison.OrdinalIgnoreCase)))
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});
builder.Services.AddSignalR();
builder.Services.AddSingleton<PeopleEditingTracker>();
builder.Services.AddOpenApi();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();
app.UseCors("LocalClientApps");

var peopleLock = new object();
var people = new List<Person>
{
    new Person(1, "Mina Patel", "Product Strategy Lead", "Toronto", "mina.patel@example.com"),
    new Person(2, "Jonah Reed", "Platform Engineer", "Montreal", "jonah.reed@example.com"),
    new Person(3, "Alina Cho", "Delivery Manager", "Vancouver", "alina.cho@example.com"),
    new Person(4, "Noah Bennett", "Business Analyst", "Calgary", "noah.bennett@example.com"),
    new Person(5, "Sofia Nguyen", "UX Researcher", "Ottawa", "sofia.nguyen@example.com")
};

app.MapGet("/api/people", () =>
{
    lock (peopleLock)
    {
        return TypedResults.Ok(people.ToArray());
    }
})
    .WithName("GetPeople");

app.MapPut("/api/people/{id:int}", (int id, UpdatePersonRequest request) =>
{
    if (string.IsNullOrWhiteSpace(request.Name)
        || string.IsNullOrWhiteSpace(request.Role)
        || string.IsNullOrWhiteSpace(request.Location)
        || string.IsNullOrWhiteSpace(request.Email))
    {
        return Results.ValidationProblem(new Dictionary<string, string[]>
        {
            ["person"] = ["Name, role, location, and email are required."]
        });
    }

    if (!request.Email.Contains('@'))
    {
        return Results.ValidationProblem(new Dictionary<string, string[]>
        {
            ["email"] = ["Email must contain '@'."]
        });
    }

    lock (peopleLock)
    {
        var currentIndex = people.FindIndex(person => person.Id == id);

        if (currentIndex < 0)
        {
            return Results.NotFound();
        }

        var updatedPerson = new Person(
            id,
            request.Name.Trim(),
            request.Role.Trim(),
            request.Location.Trim(),
            request.Email.Trim());

        people[currentIndex] = updatedPerson;
        return Results.Ok(updatedPerson);
    }
})
    .WithName("UpdatePerson");

app.MapHub<PeopleEditingHub>("/hubs/peopleEditing");

app.Run();

internal sealed record Person(int Id, string Name, string Role, string Location, string Email);
internal sealed record UpdatePersonRequest(string Name, string Role, string Location, string Email);
