// Generated by GitHub Copilot
namespace ModernApi.PeopleEditing;

using System.Collections.Concurrent;

internal sealed class PeopleEditingTracker
{
    private readonly ConcurrentDictionary<string, PersonEditingSession> sessionsByConnectionId = new();

    public IReadOnlyList<PersonEditingPresence> GetSnapshot()
    {
        var activeSessions = sessionsByConnectionId.Values.ToArray();

        return activeSessions
            .GroupBy(
                session => new { session.PersonId, session.PersonName },
                session => session.EditorName)
            .Select(group => new PersonEditingPresence(
                group.Key.PersonId,
                group.Key.PersonName,
                group
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .OrderBy(editorName => editorName, StringComparer.OrdinalIgnoreCase)
                    .ToArray()))
            .OrderBy(presence => presence.PersonName, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    public void StartEditing(string connectionId, string editorName, int personId, string personName)
    {
        sessionsByConnectionId[connectionId] = new PersonEditingSession(connectionId, editorName, personId, personName);
    }

    public bool StopEditing(string connectionId)
    {
        return sessionsByConnectionId.TryRemove(connectionId, out _);
    }
}

internal sealed record PersonEditingPresence(int PersonId, string PersonName, string[] Editors);

internal sealed record PersonEditingSession(
    string ConnectionId,
    string EditorName,
    int PersonId,
    string PersonName);