// Generated by GitHub Copilot
namespace ModernApi.PeopleEditing;

using Microsoft.AspNetCore.SignalR;

internal sealed class PeopleEditingHub(PeopleEditingTracker tracker) : Hub
{
    public override async Task OnConnectedAsync()
    {
        await Clients.Caller.SendAsync("EditingStateChanged", tracker.GetSnapshot());
        await base.OnConnectedAsync();
    }

    public override async Task OnDisconnectedAsync(Exception? exception)
    {
        if (tracker.StopEditing(Context.ConnectionId))
        {
            await BroadcastEditingState();
        }

        await base.OnDisconnectedAsync(exception);
    }

    public async Task StartEditing(StartEditingRequest request)
    {
        if (request.PersonId <= 0)
        {
            throw new HubException("A valid person identifier is required.");
        }

        if (string.IsNullOrWhiteSpace(request.PersonName))
        {
            throw new HubException("A person name is required.");
        }

        tracker.StartEditing(
            Context.ConnectionId,
            NormalizeEditorName(request.EditorName),
            request.PersonId,
            request.PersonName.Trim());

        await BroadcastEditingState();
    }

    public async Task StopEditing()
    {
        if (tracker.StopEditing(Context.ConnectionId))
        {
            await BroadcastEditingState();
        }
    }

    private Task BroadcastEditingState()
    {
        return Clients.All.SendAsync("EditingStateChanged", tracker.GetSnapshot());
    }

    private static string NormalizeEditorName(string? editorName)
    {
        var normalizedName = string.IsNullOrWhiteSpace(editorName)
            ? "Anonymous user"
            : editorName.Trim();

        return normalizedName.Length <= 40
            ? normalizedName
            : normalizedName[..40];
    }
}

internal sealed record StartEditingRequest(int PersonId, string PersonName, string? EditorName);