// Generated by GitHub Copilot
namespace ModernApi.People;

internal sealed class PeopleDirectoryService
{
    private const int DefaultPage = 1;
    private const int DefaultPageSize = 25;
    private const int MaxPageSize = 100;
    private const string DefaultSortBy = "name";
    private const string DefaultSortDirection = "asc";

    private readonly object peopleLock = new();
    private readonly List<Person> people = PeopleSeedData.CreatePeople();

    /// <summary>
    /// Gets a filtered, deterministically sorted, and paged slice of the directory.
    /// </summary>
    /// <param name="request">The incoming query parameters.</param>
    /// <returns>A page envelope containing the requested directory slice.</returns>
    public PeoplePageResponse GetPeoplePage(PeopleQueryRequest request)
    {
        var query = NormalizeQuery(request);

        lock (peopleLock)
        {
            var filteredPeople = ApplyFilters(query).ToArray();
            var orderedPeople = ApplySort(filteredPeople, query).ToArray();
            var totalCount = orderedPeople.Length;
            var totalPages = totalCount == 0
                ? 0
                : (int)Math.Ceiling(totalCount / (double)query.PageSize);
            var skip = (query.Page - 1L) * query.PageSize;
            var items = skip >= totalCount
                ? Array.Empty<Person>()
                : orderedPeople.Skip((int)skip).Take(query.PageSize).ToArray();

            return new PeoplePageResponse(
                items,
                query.Page,
                query.PageSize,
                totalCount,
                totalPages,
                totalPages > 0 && query.Page > DefaultPage,
                query.Page < totalPages,
                new PeopleAppliedFilters(
                    query.Search,
                    query.Location,
                    query.Role,
                    query.SortBy,
                    query.SortDirection));
        }
    }

    /// <summary>
    /// Updates a single seeded person when the identifier exists.
    /// </summary>
    /// <param name="id">The person identifier from the route.</param>
    /// <param name="request">The validated update payload.</param>
    /// <returns>The saved person when found; otherwise <see langword="null"/>.</returns>
    public Person? UpdatePerson(int id, UpdatePersonRequest request)
    {
        lock (peopleLock)
        {
            var currentIndex = people.FindIndex(person => person.Id == id);

            if (currentIndex < 0)
            {
                return null;
            }

            var updatedPerson = new Person(
                id,
                request.Name.Trim(),
                request.Role.Trim(),
                request.Location.Trim(),
                request.Email.Trim());

            people[currentIndex] = updatedPerson;
            return updatedPerson;
        }
    }

    /// <summary>
    /// Normalizes incoming query values so paging and filtering behavior stays predictable.
    /// </summary>
    /// <param name="request">The incoming query parameters.</param>
    /// <returns>The normalized query values used by the directory service.</returns>
    private static PeopleQuery NormalizeQuery(PeopleQueryRequest request)
    {
        return new PeopleQuery(
            request.Page is > 0 ? request.Page.Value : DefaultPage,
            request.PageSize is > 0 ? Math.Min(request.PageSize.Value, MaxPageSize) : DefaultPageSize,
            NormalizeFilter(request.Search),
            NormalizeFilter(request.Location),
            NormalizeFilter(request.Role),
            NormalizeSortBy(request.SortBy),
            NormalizeSortDirection(request.SortDirection));
    }

    /// <summary>
    /// Trims string filters and converts blank values into nulls.
    /// </summary>
    /// <param name="value">The raw filter value.</param>
    /// <returns>A trimmed filter value or <see langword="null"/>.</returns>
    private static string? NormalizeFilter(string? value)
    {
        var normalizedValue = value?.Trim();
        return string.IsNullOrWhiteSpace(normalizedValue) ? null : normalizedValue;
    }

    /// <summary>
    /// Normalizes the sort field to the supported API contract.
    /// </summary>
    /// <param name="sortBy">The requested sort field.</param>
    /// <returns>A supported sort field name.</returns>
    private static string NormalizeSortBy(string? sortBy)
    {
        return NormalizeFilter(sortBy)?.ToLowerInvariant() switch
        {
            "id" => "id",
            "location" => "location",
            "role" => "role",
            "email" => "email",
            _ => DefaultSortBy
        };
    }

    /// <summary>
    /// Normalizes the sort direction to ascending or descending.
    /// </summary>
    /// <param name="sortDirection">The requested sort direction.</param>
    /// <returns>A supported sort direction.</returns>
    private static string NormalizeSortDirection(string? sortDirection)
    {
        return NormalizeFilter(sortDirection)?.ToLowerInvariant() == "desc"
            ? "desc"
            : DefaultSortDirection;
    }

    /// <summary>
    /// Applies the supported server-side filters to the in-memory directory.
    /// </summary>
    /// <param name="query">The normalized query values.</param>
    /// <returns>The filtered people sequence.</returns>
    private IEnumerable<Person> ApplyFilters(PeopleQuery query)
    {
        var filteredPeople = people.AsEnumerable();

        if (query.Search is not null)
        {
            filteredPeople = filteredPeople.Where(person =>
                Contains(person.Name, query.Search)
                || Contains(person.Role, query.Search)
                || Contains(person.Location, query.Search)
                || Contains(person.Email, query.Search));
        }

        if (query.Location is not null)
        {
            filteredPeople = filteredPeople.Where(person =>
                person.Location.Equals(query.Location, StringComparison.OrdinalIgnoreCase));
        }

        if (query.Role is not null)
        {
            filteredPeople = filteredPeople.Where(person =>
                person.Role.Equals(query.Role, StringComparison.OrdinalIgnoreCase));
        }

        return filteredPeople;
    }

    /// <summary>
    /// Applies deterministic sorting before the page slice is selected.
    /// </summary>
    /// <param name="filteredPeople">The filtered people sequence.</param>
    /// <param name="query">The normalized query values.</param>
    /// <returns>The deterministically ordered people sequence.</returns>
    private static IEnumerable<Person> ApplySort(IEnumerable<Person> filteredPeople, PeopleQuery query)
    {
        return (query.SortBy, query.SortDirection) switch
        {
            ("id", "desc") => filteredPeople.OrderByDescending(person => person.Id),
            ("id", _) => filteredPeople.OrderBy(person => person.Id),
            ("location", "desc") => filteredPeople
                .OrderByDescending(person => person.Location, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id),
            ("location", _) => filteredPeople
                .OrderBy(person => person.Location, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id),
            ("role", "desc") => filteredPeople
                .OrderByDescending(person => person.Role, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id),
            ("role", _) => filteredPeople
                .OrderBy(person => person.Role, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id),
            ("email", "desc") => filteredPeople
                .OrderByDescending(person => person.Email, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id),
            ("email", _) => filteredPeople
                .OrderBy(person => person.Email, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id),
            ("name", "desc") => filteredPeople
                .OrderByDescending(person => person.Name, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id),
            _ => filteredPeople
                .OrderBy(person => person.Name, StringComparer.OrdinalIgnoreCase)
                .ThenBy(person => person.Id)
        };
    }

    /// <summary>
    /// Performs case-insensitive substring matching for the search filter.
    /// </summary>
    /// <param name="value">The record value being inspected.</param>
    /// <param name="search">The normalized search text.</param>
    /// <returns><see langword="true"/> when the search text appears in the value.</returns>
    private static bool Contains(string value, string search)
    {
        return value.Contains(search, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Represents the normalized query values used by the directory service.
    /// </summary>
    /// <param name="Page">The normalized 1-based page number.</param>
    /// <param name="PageSize">The normalized page size.</param>
    /// <param name="Search">The normalized free-text search value.</param>
    /// <param name="Location">The normalized location filter.</param>
    /// <param name="Role">The normalized role filter.</param>
    /// <param name="SortBy">The normalized sort field.</param>
    /// <param name="SortDirection">The normalized sort direction.</param>
    private sealed record PeopleQuery(
        int Page,
        int PageSize,
        string? Search,
        string? Location,
        string? Role,
        string SortBy,
        string SortDirection);
}