// Generated by GitHub Copilot
namespace ModernApi.People;

/// <summary>
/// Binds the supported people directory query string parameters.
/// </summary>
internal sealed class PeopleQueryRequest
{
    public int? Page { get; set; }

    public int? PageSize { get; set; }

    public string? Search { get; set; }

    public string? Location { get; set; }

    public string? Role { get; set; }

    public string? SortBy { get; set; }

    public string? SortDirection { get; set; }
}