// Generated by GitHub Copilot
namespace ModernApi.People;

/// <summary>
/// Represents a single page of directory results plus paging metadata.
/// </summary>
internal sealed record PeoplePageResponse(
    IReadOnlyList<Person> Items,
    int Page,
    int PageSize,
    int TotalCount,
    int TotalPages,
    bool HasPreviousPage,
    bool HasNextPage,
    PeopleAppliedFilters AppliedFilters);

/// <summary>
/// Represents the normalized filters applied to a paged people query.
/// </summary>
internal sealed record PeopleAppliedFilters(
    string? Search,
    string? Location,
    string? Role,
    string SortBy,
    string SortDirection);