// Generated by GitHub Copilot
namespace ModernApi.People;

internal static class PeopleSeedData
{
    private const int TargetPeopleCount = 2500;

    private static readonly string[] FirstNames =
    [
        "Aaliyah", "Adrian", "Avery", "Bianca", "Blake", "Cameron", "Carson", "Charlotte", "Daniel", "Delia",
        "Elias", "Elise", "Ethan", "Farah", "Felix", "Gabriel", "Grace", "Hannah", "Harper", "Isaac",
        "Isla", "Jasper", "Jocelyn", "Jordan", "Kai", "Layla", "Leo", "Liam", "Lina", "Logan",
        "Mara", "Mason", "Micah", "Nadia", "Nathan", "Olivia", "Owen", "Parker", "Priya", "Quinn",
        "Riley", "Sage", "Samuel", "Talia", "Theo", "Uma", "Victoria", "Wyatt", "Xavier", "Zara"
    ];

    private static readonly string[] LastNames =
    [
        "Abbott", "Adams", "Ahmed", "Barker", "Bennett", "Brooks", "Campbell", "Carter", "Chambers", "Clark",
        "Coleman", "Collins", "Cooper", "Davis", "Diaz", "Edwards", "Ellis", "Evans", "Fisher", "Foster",
        "Garcia", "Gordon", "Grant", "Gray", "Green", "Hall", "Harris", "Hayes", "Howard", "Hughes",
        "Jackson", "Johnson", "Kelly", "King", "Lewis", "Lopez", "Martin", "Mitchell", "Morgan", "Morris",
        "Nelson", "Ortiz", "Parker", "Powell", "Price", "Reed", "Rivera", "Robinson", "Turner", "Walker"
    ];

    private static readonly string[] Roles =
    [
        "Platform Engineer", "Product Manager", "Delivery Manager", "Business Analyst", "UX Researcher",
        "Data Architect", "QA Lead", "Scrum Master", "Solutions Architect", "Operations Manager"
    ];

    private static readonly string[] Locations =
    [
        "Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa", "Halifax",
        "Winnipeg", "Victoria", "Quebec City", "Edmonton", "Waterloo", "Mississauga"
    ];

    /// <summary>
    /// Creates the deterministic in-memory people dataset used by the API.
    /// </summary>
    /// <returns>A seeded people collection with preserved sample records.</returns>
    public static List<Person> CreatePeople()
    {
        var people = new List<Person>(TargetPeopleCount)
        {
            new(1, "Mina Patel", "Product Strategy Lead", "Toronto", "mina.patel@example.com"),
            new(2, "Jonah Reed", "Platform Engineer", "Montreal", "jonah.reed@example.com"),
            new(3, "Alina Cho", "Delivery Manager", "Vancouver", "alina.cho@example.com"),
            new(4, "Noah Bennett", "Business Analyst", "Calgary", "noah.bennett@example.com"),
            new(5, "Sofia Nguyen", "UX Researcher", "Ottawa", "sofia.nguyen@example.com")
        };

        var generatedIndex = 0;

        for (var lastNameIndex = 0; lastNameIndex < LastNames.Length && people.Count < TargetPeopleCount; lastNameIndex++)
        {
            for (var firstNameIndex = 0; firstNameIndex < FirstNames.Length && people.Count < TargetPeopleCount; firstNameIndex++)
            {
                var id = people.Count + 1;
                var firstName = FirstNames[firstNameIndex];
                var lastName = LastNames[lastNameIndex];
                var role = Roles[generatedIndex % Roles.Length];
                var location = Locations[(generatedIndex / Roles.Length) % Locations.Length];

                people.Add(new Person(
                    id,
                    $"{firstName} {lastName}",
                    role,
                    location,
                    CreateEmailAddress(firstName, lastName, id)));

                generatedIndex++;
            }
        }

        return people;
    }

    /// <summary>
    /// Creates a deterministic email address for a seeded person.
    /// </summary>
    /// <param name="firstName">The generated first name.</param>
    /// <param name="lastName">The generated last name.</param>
    /// <param name="id">The seeded identifier.</param>
    /// <returns>A unique email address derived from the seeded values.</returns>
    private static string CreateEmailAddress(string firstName, string lastName, int id)
    {
        return $"{NormalizeEmailPart(firstName)}.{NormalizeEmailPart(lastName)}.{id}@example.com";
    }

    /// <summary>
    /// Normalizes seeded name fragments into email-safe lowercase segments.
    /// </summary>
    /// <param name="value">The seeded name fragment.</param>
    /// <returns>A lowercase email segment.</returns>
    private static string NormalizeEmailPart(string value)
    {
        return value.ToLowerInvariant();
    }
}