// Generated by GitHub Copilot
namespace ModernApi.People;

/// <summary>
/// Represents a single directory row returned by the people API.
/// </summary>
internal sealed record Person(int Id, string Name, string Role, string Location, string Email);