// Generated by GitHub Copilot
namespace ModernApi.People;

/// <summary>
/// Represents the editable fields accepted by the people update endpoint.
/// </summary>
internal sealed record UpdatePersonRequest(string Name, string Role, string Location, string Email);