// Generated by GitHub Copilot
namespace ModernHost.Mvc.Controllers;

using Microsoft.AspNetCore.Mvc;
using ModernHost.Mvc.Models;

/// <summary>
/// Serves the landing page for the ASP.NET Core MVC modernization host.
/// </summary>
public sealed class HomeController(IConfiguration configuration) : Controller
{
    private const string DefaultModernApiBaseUrl = "https://localhost:7114";

    /// <summary>
    /// Renders the shared React people app host page and exposes the configured Modern API base URL.
    /// </summary>
    public IActionResult Index()
    {
        var configuredBaseUrl = configuration["ModernApiBaseUrl"];

        var model = new HomePageViewModel
        {
            PeopleApiBaseUrl = string.IsNullOrWhiteSpace(configuredBaseUrl)
                ? DefaultModernApiBaseUrl
                : configuredBaseUrl,
        };

        return View(model);
    }
}